"""TODO docstring. Document this module."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from robot_sf.benchmark.cli import cli_main

if TYPE_CHECKING:
    from pathlib import Path

SCHEMA_PATH = "robot_sf/benchmark/schemas/episode.schema.v1.json"


def _write_matrix(path: Path, repeats: int = 3) -> None:
    """TODO docstring. Document this function.

    Args:
        path: TODO docstring.
        repeats: TODO docstring.
    """
    scenarios = [
        {
            "id": "agg-smoke",
            "density": "low",
            "flow": "uni",
            "obstacle": "open",
            "groups": 0.0,
            "speed_var": "low",
            "goal_topology": "point",
            "robot_context": "embedded",
            "repeats": repeats,
        },
    ]
    import yaml  # type: ignore

    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(scenarios, f)


def test_cli_aggregate_without_ci(tmp_path: Path, capsys):
    # Prepare episodes via run
    """TODO docstring. Document this function.

    Args:
        tmp_path: TODO docstring.
        capsys: TODO docstring.
    """
    matrix_path = tmp_path / "matrix.yaml"
    _write_matrix(matrix_path, repeats=2)
    episodes = tmp_path / "episodes.jsonl"

    rc_run = cli_main(
        [
            "run",
            "--matrix",
            str(matrix_path),
            "--out",
            str(episodes),
            "--schema",
            SCHEMA_PATH,
            "--base-seed",
            "0",
            "--horizon",
            "6",
            "--dt",
            "0.1",
        ],
    )
    cap = capsys.readouterr()
    assert rc_run == 0, f"run failed: {cap.err}"

    # Aggregate without CI
    out_json = tmp_path / "summary.json"
    rc = cli_main(["aggregate", "--in", str(episodes), "--out", str(out_json)])
    cap2 = capsys.readouterr()
    assert rc == 0, f"aggregate failed: {cap2.err}"

    data = json.loads(out_json.read_text(encoding="utf-8"))
    # Default grouping is scenario_params.algo; algorithm found in algorithm_metadata.algorithm
    # Episodes generated by run command use 'simple_policy' algorithm
    assert "simple_policy" in data
    # Check that known metrics exist at least for mean/median/p95
    any_metric = next(iter(data["simple_policy"].keys()))
    stats = data["simple_policy"][any_metric]
    assert all(k in stats for k in ("mean", "median", "p95"))
    # CI keys should not be present when bootstrap_samples=0 (default)
    assert not any(k.endswith("_ci") for k in stats)


def test_cli_aggregate_with_ci_and_seed(tmp_path: Path, capsys):
    """TODO docstring. Document this function.

    Args:
        tmp_path: TODO docstring.
        capsys: TODO docstring.
    """
    matrix_path = tmp_path / "matrix.yaml"
    _write_matrix(matrix_path, repeats=3)
    episodes = tmp_path / "episodes.jsonl"

    rc_run = cli_main(
        [
            "run",
            "--matrix",
            str(matrix_path),
            "--out",
            str(episodes),
            "--schema",
            SCHEMA_PATH,
            "--base-seed",
            "0",
            "--horizon",
            "6",
            "--dt",
            "0.1",
        ],
    )
    cap = capsys.readouterr()
    assert rc_run == 0, f"run failed: {cap.err}"

    out1 = tmp_path / "summary_ci1.json"
    out2 = tmp_path / "summary_ci2.json"

    args = [
        "aggregate",
        "--in",
        str(episodes),
        "--out",
        str(out1),
        "--bootstrap-samples",
        "200",
        "--bootstrap-confidence",
        "0.9",
        "--bootstrap-seed",
        "123",
    ]
    rc1 = cli_main(args)
    cap1 = capsys.readouterr()
    assert rc1 == 0, f"aggregate ci failed: {cap1.err}"

    # Deterministic with same seed
    # Run again with same seed but a different output path to verify determinism
    args2 = args.copy()
    out_idx = args2.index("--out") + 1
    args2[out_idx] = str(out2)
    rc2 = cli_main(args2)
    cap2 = capsys.readouterr()
    assert rc2 == 0, f"aggregate ci repeat failed: {cap2.err}"

    d1 = json.loads(out1.read_text(encoding="utf-8"))
    d2 = json.loads(out2.read_text(encoding="utf-8"))

    assert "simple_policy" in d1
    # Pick a metric and verify CI keys present and shape
    _, stats = next(iter(d1["simple_policy"].items()))
    assert "mean_ci" in stats and "median_ci" in stats and "p95_ci" in stats
    assert len(stats["mean_ci"]) == 2
    assert isinstance(stats["mean_ci"][0], float)
    assert stats["mean_ci"][0] <= stats["mean_ci"][1]

    # Determinism check: summaries should be identical with same seed
    assert d1 == d2


def test_cli_aggregate_with_ci_writes_pairwise_contrasts(tmp_path: Path, capsys) -> None:
    """Aggregate CLI should write additive pairwise contrasts for paired planner inputs."""
    episodes = tmp_path / "paired_episodes.jsonl"
    with episodes.open("w", encoding="utf-8") as f:
        for seed, value_a in enumerate([1.0, 2.0, 3.0, 4.0], start=1):
            for algo, score in (("A", value_a), ("B", value_a + 2.0)):
                f.write(
                    json.dumps(
                        {
                            "episode_id": f"{algo}-{seed}",
                            "scenario_id": "paired-cli",
                            "seed": seed,
                            "scenario_params": {"algo": algo},
                            "metrics": {"score": score},
                        }
                    )
                    + "\n"
                )

    out_json = tmp_path / "summary_ci.json"
    rc = cli_main(
        [
            "aggregate",
            "--in",
            str(episodes),
            "--out",
            str(out_json),
            "--bootstrap-samples",
            "200",
            "--bootstrap-confidence",
            "0.9",
            "--bootstrap-seed",
            "123",
        ]
    )
    cap = capsys.readouterr()
    assert rc == 0, f"aggregate ci failed: {cap.err}"

    data = json.loads(out_json.read_text(encoding="utf-8"))
    score = data["pairwise_contrasts"]["A__vs__B"]["metrics"]["score"]
    assert score["n_pairs"] == 4
    assert score["delta_mean"] == 2.0
    assert score["delta_ci"] == [2.0, 2.0]
    assert data["pairwise_contrasts"]["_meta"]["correction_family"] == ["family", "metric"]
