"""Import-safe CARLA bridge surfaces for Robot-SF transfer experiments.

The package must remain usable without CARLA installed. Runtime replay integrations should call
the availability helpers before importing or invoking CARLA-specific APIs.
"""

from robot_sf_carla_bridge import docker_runtime
from robot_sf_carla_bridge.availability import (
    AVAILABILITY_SCHEMA_VERSION,
    CarlaUnavailableError,
    check_carla_availability,
    load_availability_schema,
    require_carla,
)
from robot_sf_carla_bridge.diagnostics import (
    CARLA_REPLAY_DIAGNOSTICS_SCHEMA_VERSION,
    DiagnosticsRow,
    build_carla_replay_diagnostics,
    load_carla_replay_diagnostics_schema,
    write_carla_replay_diagnostics_outputs,
)
from robot_sf_carla_bridge.docker_runtime import (
    CARLA_DOCKER_IMAGE,
    CARLA_DOCKER_RUNTIME_SCHEMA_VERSION,
    CARLA_PYTHON_API_REQUIREMENT,
    CommandResult,
    build_carla_client_health_summary,
    build_carla_server_container_command,
    run_carla_docker_live_replay,
    run_carla_docker_preflight,
    run_carla_docker_runtime_smoke,
    validate_carla_image,
)
from robot_sf_carla_bridge.export import (
    BATCH_VALIDATION_SUMMARY_SCHEMA_VERSION,
    EXPORT_MANIFEST_SCHEMA_VERSION,
    EXPORT_SCHEMA_VERSION,
    CertificateRef,
    PedestrianReplaySpec,
    Pose2D,
    RobotReplaySpec,
    ScenarioReplayRef,
    SimulationSpec,
    Waypoint2D,
    build_export_payload,
    build_export_payload_from_map_definition,
    build_export_payload_from_scenario_entry,
    build_export_payloads_from_scenario_file,
    load_batch_validation_summary_schema,
    load_export_manifest_payloads,
    load_export_manifest_schema,
    load_export_schema,
    read_export_manifest,
    read_export_payload,
    resolve_export_manifest_payload_paths,
    validate_export_payload,
    write_export_payload,
    write_export_records,
)
from robot_sf_carla_bridge.live_replay import (
    T1_ORACLE_LIVE_REPLAY_SCHEMA_VERSION,
    carla_planar_twist_to_robot_sf,
    robot_sf_planar_twist_to_carla,
    robot_sf_pose_to_carla_transform,
    run_t1_oracle_live_replay_against_server,
)
from robot_sf_carla_bridge.parity import (
    DEFAULT_PARITY_METRICS,
    MetricParityRow,
    compare_oracle_replay_metrics,
)
from robot_sf_carla_bridge.parity_bundle_preflight import (
    PREFLIGHT_SCHEMA_VERSION,
    check_parity_bundle_readiness,
    evaluate_payload_metadata,
)
from robot_sf_carla_bridge.replay_smoke import (
    T1_ORACLE_REPLAY_SMOKE_SCHEMA_VERSION,
    build_t1_oracle_replay_smoke_setup,
    select_t0_export_payload,
    validate_t1_replay_catalog_payload,
)
from robot_sf_carla_bridge.schema_catalog import (
    SCHEMA_CATALOG_VERSION,
    list_carla_bridge_schema_catalog,
    load_schema_catalog_schema,
)

__all__ = [
    "AVAILABILITY_SCHEMA_VERSION",
    "BATCH_VALIDATION_SUMMARY_SCHEMA_VERSION",
    "CARLA_DOCKER_IMAGE",
    "CARLA_DOCKER_RUNTIME_SCHEMA_VERSION",
    "CARLA_PYTHON_API_REQUIREMENT",
    "CARLA_REPLAY_DIAGNOSTICS_SCHEMA_VERSION",
    "DEFAULT_PARITY_METRICS",
    "EXPORT_MANIFEST_SCHEMA_VERSION",
    "EXPORT_SCHEMA_VERSION",
    "PREFLIGHT_SCHEMA_VERSION",
    "SCHEMA_CATALOG_VERSION",
    "T1_ORACLE_LIVE_REPLAY_SCHEMA_VERSION",
    "T1_ORACLE_REPLAY_SMOKE_SCHEMA_VERSION",
    "CarlaUnavailableError",
    "CertificateRef",
    "CommandResult",
    "DiagnosticsRow",
    "MetricParityRow",
    "PedestrianReplaySpec",
    "Pose2D",
    "RobotReplaySpec",
    "ScenarioReplayRef",
    "SimulationSpec",
    "Waypoint2D",
    "build_carla_client_health_summary",
    "build_carla_replay_diagnostics",
    "build_carla_server_container_command",
    "build_export_payload",
    "build_export_payload_from_map_definition",
    "build_export_payload_from_scenario_entry",
    "build_export_payloads_from_scenario_file",
    "build_t1_oracle_replay_smoke_setup",
    "carla_planar_twist_to_robot_sf",
    "check_carla_availability",
    "check_parity_bundle_readiness",
    "compare_oracle_replay_metrics",
    "docker_runtime",
    "evaluate_payload_metadata",
    "list_carla_bridge_schema_catalog",
    "load_availability_schema",
    "load_batch_validation_summary_schema",
    "load_carla_replay_diagnostics_schema",
    "load_export_manifest_payloads",
    "load_export_manifest_schema",
    "load_export_schema",
    "load_schema_catalog_schema",
    "read_export_manifest",
    "read_export_payload",
    "require_carla",
    "resolve_export_manifest_payload_paths",
    "robot_sf_planar_twist_to_carla",
    "robot_sf_pose_to_carla_transform",
    "run_carla_docker_live_replay",
    "run_carla_docker_preflight",
    "run_carla_docker_runtime_smoke",
    "run_t1_oracle_live_replay_against_server",
    "select_t0_export_payload",
    "validate_carla_image",
    "validate_export_payload",
    "validate_t1_replay_catalog_payload",
    "write_carla_replay_diagnostics_outputs",
    "write_export_payload",
    "write_export_records",
]
