"""Render a static micro-scale pedestrian-simulation snapshot for publications.

Purpose:
    Produce an informative, top-down "microscopic simulation" figure showing the
    individual-agent perspective: a handful of pedestrians (each with a velocity
    vector), the robot and its goal, and a wall obstacle. Pedestrian motion is
    generated by the actual pysocialforce engine that backs robot_sf, so the
    positions/velocities are real simulator output, not hand-drawn clip art.

    Visual conventions (colours, radii) mirror robot_sf's pygame ``SimulationView``
    so the matplotlib render reads as the same simulator:
        - robot   : blue,  radius 1.0 m   (robot_sf ROBOT_COLOR / robot_radius)
        - ped     : red,   radius 0.4 m   (robot_sf PED_COLOR  / ped_radius)
        - goal    : green                  (robot_sf ROBOT_GOAL_COLOR)
        - obstacle: dark grey wall         (robot_sf OBSTACLE_COLOR)
        - bg      : white

Usage:
    uv run python examples/plotting/plot_micro_pedestrian_scene.py

Expected Output:
    - PDF (vector, LaTeX-friendly): output/figures/micro_pedestrian_simulation.pdf
    - PNG (300 DPI fallback):       output/figures/micro_pedestrian_simulation.png

Limitations:
    - The robot/goal are overlaid as a schematic ego agent; only the pedestrians
      are advanced by pysocialforce. No HUD/title text is baked into the figure.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, FancyArrow
from pysocialforce import Simulator

from robot_sf.common.artifact_paths import resolve_artifact_path

# --- robot_sf SimulationView semantics (RGB 0-255 -> matplotlib 0-1) ----------
ROBOT_COLOR = (0 / 255, 0 / 255, 200 / 255)
PED_COLOR = (255 / 255, 50 / 255, 50 / 255)
GOAL_COLOR = (0 / 255, 204 / 255, 102 / 255)
OBSTACLE_COLOR = (20 / 255, 30 / 255, 20 / 255)
ROBOT_RADIUS = 1.0
PED_RADIUS = 0.4

# Velocity-vector lookahead: arrow length = velocity (m/s) * VEL_LOOKAHEAD_S.
VEL_LOOKAHEAD_S = 0.7


def build_micro_scene() -> tuple[np.ndarray, list[tuple[float, float, float, float]]]:
    """Define a small open-plaza micro scene of pedestrians and a wall.

    Returns:
        (state, obstacles) where ``state`` rows are
        ``[x, y, vx, vy, goal_x, goal_y, tau]`` and ``obstacles`` are line
        segments ``(x_start, x_end, y_start, y_end)`` in metres.
    """
    # 7 pedestrians crossing a shared space from several directions, spread so
    # the snapshot stays legible after a short integration window.
    # Columns: x, y, vx, vy, goal_x, goal_y, tau
    state = np.array(
        [
            [0.8, 1.8, 1.2, 0.0, 12.5, 2.0, 0.5],
            [1.0, 3.5, 1.2, 0.0, 12.5, 3.4, 0.5],
            [12.6, 7.6, -1.2, 0.0, 0.6, 7.0, 0.5],
            [12.2, 6.1, -1.2, 0.0, 0.6, 5.6, 0.5],
            [2.6, 7.9, 0.9, -0.9, 11.0, 1.6, 0.5],
            [9.6, 0.9, 0.0, 1.2, 9.2, 8.6, 0.5],
            [11.0, 8.3, -0.9, -0.9, 3.0, 1.2, 0.5],
        ],
    )

    # A single straight wall the pedestrians must flow around (horizontal segment).
    obstacles = [(4.2, 8.2, 4.7, 4.7)]
    return state, obstacles


def add_velocity_quiver(ax, positions: np.ndarray, velocities: np.ndarray) -> None:
    """Draw a short heading+speed arrow per pedestrian (0.7 s lookahead)."""
    for (x, y), (vx, vy) in zip(positions, velocities, strict=True):
        speed = float(np.hypot(vx, vy))
        if speed < 1e-3:
            continue
        dx, dy = vx * VEL_LOOKAHEAD_S, vy * VEL_LOOKAHEAD_S
        ax.add_patch(
            FancyArrow(
                x,
                y,
                dx,
                dy,
                width=0.04,
                head_width=0.28,
                head_length=0.28,
                length_includes_head=True,
                color="black",
                zorder=5,
            ),
        )


def add_scale_bar(ax, x0: float, y0: float, length_m: float = 2.0) -> None:
    """Draw a horizontal scale bar of ``length_m`` metres with a label."""
    ax.plot([x0, x0 + length_m], [y0, y0], color="black", lw=2.5, solid_capstyle="butt", zorder=6)
    for xt in (x0, x0 + length_m):
        ax.plot([xt, xt], [y0 - 0.12, y0 + 0.12], color="black", lw=2.5, zorder=6)
    ax.text(
        x0 + length_m / 2,
        y0 + 0.28,
        f"{length_m:.0f} m",
        ha="center",
        va="bottom",
        fontsize=9,
    )


def main() -> None:
    """Build the micro scene, advance pedestrians, and export PDF + PNG."""
    # LaTeX-friendly export settings (see docs/dev_guide.md).
    plt.rcParams.update(
        {
            "savefig.bbox": "tight",
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.size": 9,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
        },
    )

    state, obstacles = build_micro_scene()
    sim = Simulator(state=state.copy(), obstacles=obstacles)
    # Advance with the real social-force engine so positions/velocities are
    # genuine simulator output rather than the hand-set initial conditions.
    sim.step(18)

    positions = np.asarray(sim.peds.pos())
    velocities = np.asarray(sim.peds.vel())

    # --- Schematic ego robot + goal (overlaid; not part of pysocialforce) -----
    robot_pos = np.array([5.4, 2.3])
    robot_goal = np.array([8.8, 7.2])
    robot_heading = robot_goal - robot_pos
    robot_heading = robot_heading / np.linalg.norm(robot_heading)
    robot_speed = 1.0  # m/s

    fig, ax = plt.subplots(figsize=(7.0, 5.2))

    # Wall obstacle(s).
    for x1, x2, y1, y2 in obstacles:
        ax.plot([x1, x2], [y1, y2], color=OBSTACLE_COLOR, lw=6, solid_capstyle="round", zorder=2)

    # Pedestrians: filled red disks at true radius + velocity arrows.
    for x, y in positions:
        ax.add_patch(Circle((x, y), PED_RADIUS, color=PED_COLOR, ec="black", lw=0.6, zorder=4))
    add_velocity_quiver(ax, positions, velocities)

    # Robot goal (green ring) and a connecting dashed line.
    ax.plot(
        [robot_pos[0], robot_goal[0]],
        [robot_pos[1], robot_goal[1]],
        ls="--",
        color=GOAL_COLOR,
        lw=1.2,
        zorder=3,
    )
    ax.add_patch(Circle(tuple(robot_goal), 0.5, fill=False, ec=GOAL_COLOR, lw=2.5, zorder=4))
    ax.plot(*robot_goal, marker="*", color=GOAL_COLOR, ms=12, zorder=5)

    # Robot: blue disk at true radius + heading arrow.
    ax.add_patch(
        Circle(tuple(robot_pos), ROBOT_RADIUS, color=ROBOT_COLOR, ec="black", lw=0.8, zorder=4)
    )
    rdx, rdy = robot_heading * robot_speed * VEL_LOOKAHEAD_S
    ax.add_patch(
        FancyArrow(
            robot_pos[0],
            robot_pos[1],
            rdx,
            rdy,
            width=0.05,
            head_width=0.34,
            head_length=0.34,
            length_includes_head=True,
            color="white",
            zorder=5,
        ),
    )

    add_scale_bar(ax, x0=0.6, y0=0.3, length_m=2.0)

    # Compact legend identifying the agent classes.
    handles = [
        plt.Line2D(
            [],
            [],
            marker="o",
            ls="",
            mfc=ROBOT_COLOR,
            mec="black",
            ms=11,
            label="Robot (ego agent)",
        ),
        plt.Line2D([], [], marker="o", ls="", mfc=PED_COLOR, mec="black", ms=8, label="Pedestrian"),
        plt.Line2D(
            [], [], marker="*", ls="", mfc=GOAL_COLOR, mec=GOAL_COLOR, ms=12, label="Robot goal"
        ),
        plt.Line2D([], [], color="black", lw=2, label="Velocity (0.7 s)"),
        plt.Line2D([], [], color=OBSTACLE_COLOR, lw=5, label="Wall / obstacle"),
    ]
    ax.legend(handles=handles, loc="upper left", framealpha=0.9, borderaxespad=0.4)

    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_xlim(-0.3, 13.3)
    ax.set_ylim(-0.3, 9.3)
    ax.set_aspect("equal")
    ax.grid(True, ls=":", lw=0.5, color="0.8", zorder=0)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    out_pdf = resolve_artifact_path(Path("output/figures/micro_pedestrian_simulation.pdf"))
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(str(out_pdf))
    print(f"Wrote {out_pdf}")

    out_png = resolve_artifact_path(Path("output/figures/micro_pedestrian_simulation.png"))
    fig.savefig(str(out_png), dpi=300)
    print(f"Wrote {out_png}")

    plt.close(fig)


if __name__ == "__main__":
    main()
