"""Render a static micro-scale pedestrian-simulation snapshot for publications.

Purpose:
    Produce an informative, top-down "microscopic simulation" figure showing the
    individual-agent perspective: a handful of pedestrians (each with a velocity
    vector), the robot and its goal, and a wall obstacle. Pedestrian motion is
    generated by the actual pysocialforce engine that backs robot_sf, so the
    positions/velocities are real simulator output, not hand-drawn clip art.

    Visual conventions (colours, radii) mirror robot_sf's pygame ``SimulationView``
    so the matplotlib render reads as the same simulator:
        - robot   : dark-blue centre marker + light-blue collision envelope disc of
          RADIUS 1.0 m, annotated explicitly. The 1.0 m is the collision radius used
          by the simulator's physics/metrics (``DifferentialDriveSettings.radius`` /
          ``DEFAULT_ROBOT_RADIUS``); the configuration carries no separate physical
          body radius, so no smaller body disc is drawn -- inventing one would
          suggest a validated vehicle footprint that the simulator does not model.
        - ped     : red,   radius 0.4 m   (robot_sf PED_COLOR  / ped_radius)
        - goal    : green                  (robot_sf ROBOT_GOAL_COLOR)
        - obstacle: dark grey wall         (robot_sf OBSTACLE_COLOR)
        - bg      : white

Usage:
    uv run python examples/plotting/plot_micro_pedestrian_scene.py

Expected Output:
    - PDF (vector, LaTeX-friendly): output/plots/micro_pedestrian_simulation.pdf
    - PNG (300 DPI fallback):       output/plots/micro_pedestrian_simulation.png

Limitations:
    - The robot/goal are overlaid as a schematic ego agent; only the pedestrians
      are advanced by pysocialforce. No HUD/title text is baked into the figure.

Figure-quality note:
    - The legend's "Velocity" swatch is a small FancyArrow proxy (via a custom
      HandlerPatch) so it carries the same arrowhead as the velocity arrows drawn
      on the pedestrians, instead of a plain line.
    - The dashed green robot-to-goal vector has its own legend entry.
    - The plot keeps metric axes (x/y in metres, equal aspect) and drops the
      separate scale bar, since the axes already make the spatial scale explicit
      and the two were redundant.
    - Design-at-final-size print contract: the canvas is 5.2 in wide and the PDF
      is saved WITHOUT a tight-bbox crop, so its natural width equals the print
      column width exactly (no silent downscaling) and every font stays >= 8 pt
      on the page. A radius tick with an "r = 1.0 m" annotation makes the
      envelope's radius (not diameter) unambiguous.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.legend_handler import HandlerPatch
from matplotlib.patches import Circle, FancyArrow
from pysocialforce import Simulator

from robot_sf.common.artifact_paths import resolve_artifact_path

# --- robot_sf SimulationView semantics (RGB 0-255 -> matplotlib 0-1) ----------
ROBOT_COLOR = (0 / 255, 0 / 255, 200 / 255)
ROBOT_ENVELOPE_FACE = (0.72, 0.82, 0.93)  # light blue: collision envelope, not a body
PED_COLOR = (255 / 255, 50 / 255, 50 / 255)
GOAL_COLOR = (0 / 255, 204 / 255, 102 / 255)
OBSTACLE_COLOR = (20 / 255, 30 / 255, 20 / 255)
# Collision RADIUS used by the simulator's physics/metrics (the authoritative
# default: DifferentialDriveSettings.radius = DEFAULT_ROBOT_RADIUS = 1.0 m).
# The config defines no separate physical body radius, so the render shows the
# envelope disc plus a centre marker instead of a fictitious body circle.
ROBOT_ENVELOPE_RADIUS = 1.0
PED_RADIUS = 0.4

# Print contract: design at the final included width so LaTeX never rescales the
# PDF and the fonts below print at their nominal sizes (>= 8 pt).
FIGURE_WIDTH_IN = 5.2
FIGURE_HEIGHT_IN = 4.75  # scene panel + the two-column legend row above it

# Velocity-vector lookahead: arrow length = velocity (m/s) * VEL_LOOKAHEAD_S.
VEL_LOOKAHEAD_S = 0.7


def build_micro_scene() -> tuple[np.ndarray, list[tuple[float, float, float, float]]]:
    """Define a small open-plaza micro scene of pedestrians and a wall.

    Returns:
        (state, obstacles) where ``state`` rows are
        ``[x, y, vx, vy, goal_x, goal_y, tau]`` and ``obstacles`` are line
        segments ``(x_start, x_end, y_start, y_end)`` in metres.
    """
    # 7 pedestrians crossing a shared space from several directions, spread so
    # the snapshot stays legible after a short integration window.
    # Columns: x, y, vx, vy, goal_x, goal_y, tau
    state = np.array(
        [
            [0.8, 1.8, 1.2, 0.0, 12.5, 2.0, 0.5],
            [1.0, 3.5, 1.2, 0.0, 12.5, 3.4, 0.5],
            [12.6, 7.6, -1.2, 0.0, 0.6, 7.0, 0.5],
            [12.2, 6.1, -1.2, 0.0, 0.6, 5.6, 0.5],
            [2.6, 7.9, 0.9, -0.9, 11.0, 1.6, 0.5],
            [9.6, 0.9, 0.0, 1.2, 9.2, 8.6, 0.5],
            [11.0, 8.3, -0.9, -0.9, 3.0, 1.2, 0.5],
        ],
    )

    # A single straight wall the pedestrians must flow around (horizontal segment).
    obstacles = [(4.2, 8.2, 4.7, 4.7)]
    return state, obstacles


def add_velocity_quiver(ax, positions: np.ndarray, velocities: np.ndarray) -> None:
    """Draw a short heading+speed arrow per pedestrian (0.7 s lookahead)."""
    for (x, y), (vx, vy) in zip(positions, velocities, strict=True):
        speed = float(np.hypot(vx, vy))
        if speed < 1e-3:
            continue
        dx, dy = vx * VEL_LOOKAHEAD_S, vy * VEL_LOOKAHEAD_S
        ax.add_patch(
            FancyArrow(
                x,
                y,
                dx,
                dy,
                width=0.04,
                head_width=0.28,
                head_length=0.28,
                length_includes_head=True,
                color="black",
                zorder=5,
            ),
        )


class _FancyArrowLegendHandler(HandlerPatch):
    """Draw a small FancyArrow proxy for legend entries.

    Used so the "Velocity" legend swatch carries the same arrowhead as the
    velocity arrows drawn on the pedestrians, instead of a plain line segment.
    """

    def create_artists(
        self,
        legend,
        orig_handle,
        xdescent,
        ydescent,
        width,
        height,
        fontsize,
        trans,
    ):
        arrow = FancyArrow(
            -xdescent,
            -ydescent + 0.5 * height,
            width,
            0,
            width=0.10 * height,
            head_width=0.55 * height,
            head_length=0.4 * width,
            length_includes_head=True,
            color=orig_handle.get_facecolor(),
        )
        arrow.set_transform(trans)
        return [arrow]


def main() -> None:
    """Build the micro scene, advance pedestrians, and export PDF + PNG."""
    # LaTeX-friendly export settings (see docs/dev_guide.md). No tight-bbox crop:
    # the canvas is designed at the final print width, so the saved PDF's natural
    # width must equal the figure width exactly.
    plt.rcParams.update(
        {
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "font.size": 9,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
        },
    )

    state, obstacles = build_micro_scene()
    sim = Simulator(state=state.copy(), obstacles=obstacles)
    # Advance with the real social-force engine so positions/velocities are
    # genuine simulator output rather than the hand-set initial conditions.
    sim.step(18)

    positions = np.asarray(sim.peds.pos())
    velocities = np.asarray(sim.peds.vel())

    # --- Schematic ego robot + goal (overlaid; not part of pysocialforce) -----
    # Goal placed in free space (clear of every pedestrian disc at this frame)
    # so the green goal ring does not overlap a red pedestrian.
    robot_pos = np.array([5.4, 2.3])
    robot_goal = np.array([8.0, 7.8])
    robot_heading = robot_goal - robot_pos
    robot_heading_norm = np.linalg.norm(robot_heading)
    if robot_heading_norm > 0:
        robot_heading = robot_heading / robot_heading_norm
    else:
        robot_heading = np.zeros_like(robot_heading)
    robot_speed = 1.0  # m/s

    fig, ax = plt.subplots(figsize=(FIGURE_WIDTH_IN, FIGURE_HEIGHT_IN), constrained_layout=True)

    # Wall obstacle(s).
    for x1, x2, y1, y2 in obstacles:
        ax.plot([x1, x2], [y1, y2], color=OBSTACLE_COLOR, lw=6, solid_capstyle="round", zorder=2)

    # Pedestrians: filled red disks at true radius + velocity arrows.
    for x, y in positions:
        ax.add_patch(Circle((x, y), PED_RADIUS, color=PED_COLOR, ec="black", lw=0.6, zorder=4))
    add_velocity_quiver(ax, positions, velocities)

    # Robot goal (green ring) and a connecting dashed line.
    ax.plot(
        [robot_pos[0], robot_goal[0]],
        [robot_pos[1], robot_goal[1]],
        ls="--",
        color=GOAL_COLOR,
        lw=1.2,
        zorder=3,
    )
    ax.add_patch(Circle(tuple(robot_goal), 0.5, fill=False, ec=GOAL_COLOR, lw=2.5, zorder=4))
    ax.plot(*robot_goal, marker="*", color=GOAL_COLOR, ms=12, zorder=5)

    # Robot: light-blue collision-envelope disc at the config-backed collision
    # RADIUS (1.0 m) + dark-blue centre marker + heading arrow. The simulator
    # config carries no separate physical body radius, so no smaller body disc
    # is drawn; the envelope is annotated as what it is.
    ax.add_patch(
        Circle(
            tuple(robot_pos),
            ROBOT_ENVELOPE_RADIUS,
            facecolor=ROBOT_ENVELOPE_FACE,
            edgecolor=ROBOT_COLOR,
            linewidth=1.1,
            zorder=4,
        )
    )
    ax.plot(
        robot_pos[0],
        robot_pos[1],
        marker="o",
        markersize=5,
        color=ROBOT_COLOR,
        linestyle="none",
        zorder=6,
    )
    # Radius tick + label: 1.0 m is the envelope RADIUS, not its diameter. The
    # tick points to the lower right, where the scene leaves free space.
    tick_direction = np.array([np.cos(np.radians(-35.0)), np.sin(np.radians(-35.0))])
    tick_end = robot_pos + ROBOT_ENVELOPE_RADIUS * tick_direction
    ax.plot(
        [robot_pos[0], tick_end[0]],
        [robot_pos[1], tick_end[1]],
        color=ROBOT_COLOR,
        linewidth=0.9,
        zorder=5,
    )
    ax.annotate(
        "r = 1.0 m",
        tick_end,
        xytext=(3, -2),
        textcoords="offset points",
        color=ROBOT_COLOR,
        fontsize=8,
        ha="left",
        va="top",
    )
    rdx, rdy = robot_heading * robot_speed * VEL_LOOKAHEAD_S
    ax.add_patch(
        FancyArrow(
            robot_pos[0],
            robot_pos[1],
            rdx,
            rdy,
            width=0.05,
            head_width=0.34,
            head_length=0.34,
            length_includes_head=True,
            color=ROBOT_COLOR,
            zorder=5,
        ),
    )

    # Scale bar intentionally omitted: the metric axes (x/y in metres) already
    # make the spatial scale explicit, so a separate scale bar is redundant.

    # Compact legend identifying the agent classes.
    velocity_proxy = FancyArrow(
        0, 0, 1, 0, width=0.01, facecolor="black", edgecolor="none", label="Velocity (0.7 s)"
    )
    goal_vector_handle = plt.Line2D(
        [], [], ls="--", color=GOAL_COLOR, lw=1.2, label="Robot goal vector"
    )
    handles = [
        plt.Line2D(
            [],
            [],
            marker="o",
            ls="",
            mfc=ROBOT_ENVELOPE_FACE,
            mec=ROBOT_COLOR,
            ms=11,
            label="Collision envelope (r = 1.0 m)",
        ),
        plt.Line2D(
            [],
            [],
            marker="o",
            ls="",
            mfc=ROBOT_COLOR,
            mec=ROBOT_COLOR,
            ms=5,
            label="Robot center (ego agent)",
        ),
        plt.Line2D(
            [],
            [],
            marker="o",
            ls="",
            mfc=PED_COLOR,
            mec="black",
            ms=8,
            label="Pedestrian (r = 0.4 m)",
        ),
        plt.Line2D(
            [], [], marker="*", ls="", mfc=GOAL_COLOR, mec=GOAL_COLOR, ms=12, label="Robot goal"
        ),
        goal_vector_handle,
        velocity_proxy,
        plt.Line2D([], [], color=OBSTACLE_COLOR, lw=5, label="Wall / obstacle"),
    ]
    # The legend sits above the axes: at the 5.2 in print width an in-axes legend
    # would cover pedestrians of the rendered scene.
    ax.legend(
        handles=handles,
        loc="lower left",
        bbox_to_anchor=(0.0, 1.01, 1.0, 0.28),
        mode="expand",
        ncol=2,
        framealpha=1.0,
        borderaxespad=0.0,
        handler_map={FancyArrow: _FancyArrowLegendHandler()},
    )

    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.set_xlim(-0.3, 13.3)
    ax.set_ylim(-0.3, 9.3)
    ax.set_aspect("equal")
    ax.grid(True, ls=":", lw=0.5, color="0.8", zorder=0)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)

    out_pdf = resolve_artifact_path(Path("plots/micro_pedestrian_simulation.pdf"))
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(str(out_pdf))
    print(f"Wrote {out_pdf}")

    out_png = resolve_artifact_path(Path("plots/micro_pedestrian_simulation.png"))
    fig.savefig(str(out_png), dpi=300)
    print(f"Wrote {out_png}")

    plt.close(fig)


if __name__ == "__main__":
    main()
