name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # clone the source code containing the package version generation script
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      # make sure python is set up properly
      - name: Install Python (with dependencies)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: python -m pip install uv

      - name: Install dependencies
        run: uv sync --group=dev

      - name: Register modules under test
        run: uv pip install -e .

      - name: Run tests
        run: uv run pytest tests

      - name: Run linter
        run: uv run pylint pysocialforce
