#!/usr/bin/env python3
"""Build and validate the Robot SF ecosystem producer contract.

The committed contract is revision-invariant. It records only exported
capabilities and deterministic digests of the narrow authoritative source
selectors that define them. A separate revision envelope binds the contract
bytes to a source commit, release tag/status, and ``uv.lock`` digest.

Canonical JSON bytes are produced by the pinned :mod:`rfc8785` implementation.
Consumers can therefore validate structure, digest, and compatibility without
importing Robot SF modules.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import subprocess
import sys
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

import rfc8785
from jsonschema import Draft202012Validator, FormatChecker  # type: ignore[import-untyped]
from jsonschema.exceptions import SchemaError  # type: ignore[import-untyped]

CONTRACT_SCHEMA_VERSION = "robot_sf_ecosystem_contract.v1"
REVISION_ENVELOPE_SCHEMA_VERSION = "robot_sf_ecosystem_revision_envelope.v1"
REGISTRY_SCHEMA_VERSION = "robot_sf_ecosystem_capabilities.v1"
REQUIREMENTS_SCHEMA_VERSION = "robot_sf_ecosystem_requirements.v1"
COMPATIBILITY_REPORT_SCHEMA_VERSION = "robot_sf_ecosystem_compatibility_report.v1"
CHANGE_REPORT_SCHEMA_VERSION = "robot_sf_ecosystem_change_report.v1"
CANONICALIZATION_PROFILE = "RFC8785"
GENERATOR_VERSION = "1.0.0"
REPOSITORY_URL = "https://github.com/ll7/robot_sf_ll7"

SCRIPT_PATH = Path("scripts/tools/build_robot_sf_ecosystem_contract.py")
DEFAULT_REGISTRY_PATH = Path("robot_sf/benchmark/contracts/robot_sf_ecosystem_capabilities.v1.json")
DEFAULT_CONTRACT_SCHEMA_PATH = Path(
    "robot_sf/benchmark/schemas/robot_sf_ecosystem_contract.v1.json"
)
DEFAULT_REVISION_SCHEMA_PATH = Path(
    "robot_sf/benchmark/schemas/robot_sf_ecosystem_revision_envelope.v1.json"
)
DEFAULT_CONTRACT_PATH = Path("robot_sf/benchmark/contracts/robot_sf_ecosystem_contract.v1.json")
DEFAULT_DIGEST_PATH = Path("robot_sf/benchmark/contracts/robot_sf_ecosystem_contract.v1.sha256")
DEFAULT_LOCK_PATH = Path("uv.lock")

MINIMUM_CONSUMER_FEATURES = (
    "rfc8785.jcs.v1",
    "robot_sf.contract.capability_match.v1",
    "robot_sf.contract.change_classification.v1",
    "sha256.v1",
)
COMPATIBILITY_POLICY = {
    "match_fields": ["capability_id", "interface_major", "status", "semantics_id"],
    "whole_contract_digest_role": "provenance_only",
    "revision_fields_role": "provenance_only",
    "additive_change_rule": "same_contract_major_and_explicit_additive_record",
    "deprecation_rule": "same_contract_major_and_explicit_deprecation_record",
    "breaking_change_rule": "new_contract_major_and_explicit_breaking_record",
}

_SEMVER_RE = re.compile(r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$")
_IDENTIFIER_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")
_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_INPUT_KINDS = {
    "json_schema",
    "toml_project_field",
    "toml_project_script",
    "python_constant",
    "python_symbol",
    "python_test",
}
_CAPABILITY_KINDS = {"cli", "schema", "protocol", "artifact_identity"}
_STATUSES = {"stable", "beta", "experimental", "deprecated"}
_CONTROL_INPUT_IDS = {"contract.capability_registry.v1", "contract.schema.v1"}


class ContractError(ValueError):
    """Raised when a contract, registry, requirement, or envelope is invalid."""


class ContractDriftError(ContractError):
    """Raised when committed generated bytes are stale."""


class CompatibilityError(ContractError):
    """Raised when a valid contract does not meet compatibility requirements."""


@dataclass(frozen=True, slots=True)
class ResolvedInput:
    """One authoritative selector resolved from repository source."""

    public_record: dict[str, Any]
    value: Any


def repository_root() -> Path:
    """Return the checkout root derived from this script location."""
    return Path(__file__).resolve().parents[2]


def canonical_bytes(value: Any) -> bytes:
    """Return RFC 8785 JSON Canonicalization Scheme bytes for ``value``.

    Raises:
        ContractError: If the value is outside the RFC 8785/I-JSON domain.
    """
    try:
        return rfc8785.dumps(value)
    except (rfc8785.CanonicalizationError, TypeError, ValueError) as exc:
        raise ContractError(f"value cannot be canonicalized with RFC 8785: {exc}") from exc


def sha256_bytes(payload: bytes) -> str:
    """Return the lowercase SHA-256 digest of ``payload``."""
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    """Return the lowercase SHA-256 digest of an existing file."""
    try:
        return sha256_bytes(path.read_bytes())
    except OSError as exc:
        raise ContractError(f"cannot read digest input {path}: {exc}") from exc


def _git_output(root: Path, *arguments: str) -> bytes:
    """Run one bounded read-only Git query for release provenance."""
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *arguments],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise ContractError(f"Git provenance query failed for {' '.join(arguments)}") from exc
    return result.stdout


def _verify_git_binding(
    *,
    root: Path,
    source_commit: str,
    release_status: str,
    release_tag: str | None,
    contract_relative: str,
    contract_file: Path,
    lock_relative: str,
    lock_file: Path,
) -> None:
    """Verify commit, tag target, and bound blobs in a tagged/released checkout."""
    resolved_commit = (
        _git_output(root, "rev-parse", "--verify", f"{source_commit}^{{commit}}")
        .decode("ascii")
        .strip()
    )
    if resolved_commit != source_commit:
        raise ContractError(
            f"source_commit does not resolve to the requested Git commit: {source_commit}"
        )
    if release_status in {"tagged", "released"}:
        if not release_tag:
            raise ContractError("tagged/released envelopes require a release tag")
        tag_target = (
            _git_output(root, "rev-parse", "--verify", f"refs/tags/{release_tag}^{{commit}}")
            .decode("ascii")
            .strip()
        )
        if tag_target != source_commit:
            raise ContractError(
                f"release tag {release_tag!r} does not resolve to source_commit {source_commit}"
            )
    for relative, local_file, label in (
        (contract_relative, contract_file, "contract"),
        (lock_relative, lock_file, "lock"),
    ):
        committed_bytes = _git_output(root, "show", f"{source_commit}:{relative}")
        if sha256_bytes(committed_bytes) != sha256_file(local_file):
            raise ContractError(f"{label} bytes do not match the source commit {source_commit}")


def _reject_duplicate_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    """Build a JSON object while rejecting duplicate member names."""
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ContractError(f"duplicate JSON object key: {key!r}")
        result[key] = value
    return result


def _reject_nonfinite_token(token: str) -> None:
    """Reject non-JSON numeric constants accepted by Python's decoder."""
    raise ContractError(f"non-finite JSON number is not allowed: {token}")


def load_json(path: Path) -> Any:
    """Load UTF-8 JSON with duplicate-key and non-finite-number rejection."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise ContractError(f"cannot read JSON document {path}: {exc}") from exc
    try:
        value = json.loads(
            text,
            object_pairs_hook=_reject_duplicate_pairs,
            parse_constant=_reject_nonfinite_token,
        )
    except ContractError:
        raise
    except (json.JSONDecodeError, UnicodeError, ValueError) as exc:
        raise ContractError(f"malformed JSON document {path}: {exc}") from exc
    canonical_bytes(value)
    return value


def _mapping(value: Any, label: str) -> dict[str, Any]:
    """Return ``value`` as a plain mapping or fail with a precise label."""
    if not isinstance(value, Mapping):
        raise ContractError(f"{label} must be a JSON object")
    return dict(value)


def _sequence(value: Any, label: str) -> list[Any]:
    """Return ``value`` as a list or fail with a precise label."""
    if not isinstance(value, list):
        raise ContractError(f"{label} must be a JSON array")
    return value


def _string(value: Any, label: str) -> str:
    """Return a non-empty string or fail with a precise label."""
    if not isinstance(value, str) or not value:
        raise ContractError(f"{label} must be a non-empty string")
    return value


def _identifier(value: Any, label: str) -> str:
    """Return a normalized machine identifier or fail."""
    text = _string(value, label)
    if _IDENTIFIER_RE.fullmatch(text) is None:
        raise ContractError(f"{label} is not a valid identifier: {text!r}")
    return text


def _semver(value: Any, label: str) -> tuple[int, int, int]:
    """Parse a strict semantic version triple."""
    text = _string(value, label)
    match = _SEMVER_RE.fullmatch(text)
    if match is None:
        raise ContractError(f"{label} must be a strict semantic version, got {text!r}")
    return tuple(int(part) for part in match.groups())  # type: ignore[return-value]


def _assert_exact_keys(value: Mapping[str, Any], allowed: set[str], label: str) -> None:
    """Reject unrecognized object keys so declarations fail closed."""
    extras = sorted(set(value) - allowed)
    if extras:
        raise ContractError(f"{label} has unsupported field(s): {', '.join(extras)}")


def _normalized_repo_path(raw_path: Any, label: str) -> str:
    """Return one normalized repository-relative POSIX path."""
    text = _string(raw_path, label)
    pure = PurePosixPath(text)
    normalized = pure.as_posix()
    if (
        pure.is_absolute()
        or not pure.parts
        or ".." in pure.parts
        or "." in pure.parts
        or normalized != text
    ):
        raise ContractError(f"{label} must be a normalized repository-relative path: {text!r}")
    return normalized


def _repo_relative_path(root: Path, raw_path: Any, label: str) -> tuple[str, Path]:
    """Resolve a safe repository-relative file path inside ``root``."""
    normalized = _normalized_repo_path(raw_path, label)
    pure = PurePosixPath(normalized)
    root_resolved = root.resolve()
    resolved = (root_resolved / Path(*pure.parts)).resolve()
    try:
        resolved.relative_to(root_resolved)
    except ValueError as exc:
        raise ContractError(f"{label} escapes the repository root: {normalized!r}") from exc
    if not resolved.is_file():
        raise ContractError(f"{label} does not resolve to a public repository file: {normalized}")
    return normalized, resolved


def _path_argument(root: Path, path: Path) -> Path:
    """Resolve a CLI path relative to ``root`` unless it is already absolute."""
    return path if path.is_absolute() else root / path


def _root_relative_existing_path(root: Path, path: Path, label: str) -> tuple[str, Path]:
    """Resolve a relative or absolute path to one existing file under ``root``."""
    root_resolved = root.resolve()
    resolved = _path_argument(root_resolved, path).resolve()
    try:
        relative = resolved.relative_to(root_resolved).as_posix()
    except ValueError as exc:
        raise ContractError(f"{label} escapes the repository root: {path}") from exc
    return _repo_relative_path(root_resolved, relative, label)


def _json_path(parts: Sequence[Any]) -> str:
    """Render a jsonschema error path for human diagnostics."""
    if not parts:
        return "$"
    rendered = "$"
    for part in parts:
        rendered += f"[{part}]" if isinstance(part, int) else f".{part}"
    return rendered


def _validate_json_schema(schema: Mapping[str, Any], label: str) -> None:
    """Validate that ``schema`` is a supported Draft 2020-12 schema."""
    if schema.get("$schema") != "https://json-schema.org/draft/2020-12/schema":
        raise ContractError(f"{label} must declare JSON Schema draft 2020-12")
    if not isinstance(schema.get("$id"), str) or not schema["$id"]:
        raise ContractError(f"{label} must declare a non-empty $id")
    try:
        Draft202012Validator.check_schema(dict(schema))
    except SchemaError as exc:
        raise ContractError(f"{label} is not a valid Draft 2020-12 schema: {exc.message}") from exc


def _validate_against_schema(value: Any, schema: Mapping[str, Any], label: str) -> None:
    """Validate one value and report all schema failures deterministically."""
    validator = Draft202012Validator(dict(schema), format_checker=FormatChecker())
    errors = sorted(
        validator.iter_errors(value),
        key=lambda item: tuple(str(part) for part in item.absolute_path),
    )
    if errors:
        details = "; ".join(
            f"{_json_path(list(error.absolute_path))}: {error.message}" for error in errors
        )
        raise ContractError(f"{label} failed schema validation: {details}")


def _load_schema(path: Path, label: str) -> dict[str, Any]:
    """Load and meta-validate one Draft 2020-12 schema."""
    schema = _mapping(load_json(path), label)
    _validate_json_schema(schema, label)
    return schema


def _find_python_node(tree: ast.Module, selector: str, path: Path) -> ast.AST:
    """Resolve a dotted top-level/class Python symbol from an AST."""
    parts = selector.split(".")
    body: Sequence[ast.stmt] = tree.body
    current: ast.AST | None = None
    for index, part in enumerate(parts):
        matches = [
            node
            for node in body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
            and node.name == part
        ]
        if len(matches) != 1:
            raise ContractError(f"{path}: selector {selector!r} does not resolve exactly once")
        current = matches[0]
        if index < len(parts) - 1:
            if not isinstance(current, ast.ClassDef):
                raise ContractError(f"{path}: non-class component in selector {selector!r}")
            body = current.body
    if current is None:  # pragma: no cover - selector is already non-empty
        raise ContractError(f"{path}: empty Python selector")
    return current


def _python_constant(text: str, path: Path, selector: str) -> Any:
    """Resolve one literal top-level Python assignment without importing it."""
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as exc:
        raise ContractError(f"cannot parse authoritative Python source {path}: {exc}") from exc
    values: list[ast.AST] = []
    for node in tree.body:
        if isinstance(node, ast.Assign):
            if any(
                isinstance(target, ast.Name) and target.id == selector for target in node.targets
            ):
                values.append(node.value)
        elif (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == selector
            and node.value is not None
        ):
            values.append(node.value)
    if len(values) != 1:
        raise ContractError(f"{path}: constant {selector!r} does not resolve exactly once")
    try:
        return ast.literal_eval(values[0])
    except (ValueError, TypeError) as exc:
        raise ContractError(f"{path}: constant {selector!r} is not a literal value") from exc


def _python_symbol_projection(
    text: str, path: Path, selector: str, *, test: bool
) -> dict[str, str]:
    """Return a stable source projection for one Python symbol."""
    try:
        tree = ast.parse(text, filename=str(path))
    except SyntaxError as exc:
        raise ContractError(f"cannot parse authoritative Python source {path}: {exc}") from exc
    node = _find_python_node(tree, selector, path)
    if test:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            raise ContractError(f"{path}: test selector {selector!r} must resolve to a function")
        if not selector.rsplit(".", maxsplit=1)[-1].startswith("test_"):
            raise ContractError(f"{path}: test selector {selector!r} must start with test_")
    decorators = getattr(node, "decorator_list", [])
    start = decorators[0] if decorators else node
    start_line = getattr(start, "lineno", None)
    start_column = getattr(start, "col_offset", None)
    end_line = getattr(node, "end_lineno", None)
    end_column = getattr(node, "end_col_offset", None)
    if (
        not isinstance(start_line, int)
        or not isinstance(start_column, int)
        or not isinstance(end_line, int)
        or not isinstance(end_column, int)
    ):
        raise ContractError(f"{path}: selector {selector!r} has incomplete source positions")
    span = ast.Constant(value=None)
    span.lineno = start_line
    span.col_offset = max(0, start_column - 1) if decorators else start_column
    span.end_lineno = end_line
    span.end_col_offset = end_column
    source = ast.get_source_segment(text, span)
    if source is None:
        raise ContractError(f"{path}: cannot extract source for selector {selector!r}")
    return {"node_type": type(node).__name__, "selector": selector, "source": source}


def _toml_field(document: Mapping[str, Any], selector: str, path: Path) -> Any:
    """Resolve a dotted TOML mapping selector."""
    current: Any = document
    for part in selector.split("."):
        if not isinstance(current, Mapping) or part not in current:
            raise ContractError(f"{path}: TOML selector {selector!r} does not resolve")
        current = current[part]
    return current


def _resolve_toml_projection(
    path: Path, relative: str, kind: str, selector: str
) -> tuple[Any, dict[str, Any]]:
    """Resolve one TOML field or project-script selector."""
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
        raise ContractError(f"cannot parse authoritative TOML source {relative}: {exc}") from exc
    if kind == "toml_project_script":
        scripts = _toml_field(document, "project.scripts", path)
        if not isinstance(scripts, Mapping) or selector not in scripts:
            raise ContractError(f"{relative}: project script {selector!r} does not resolve")
        value = scripts[selector]
    else:
        value = _toml_field(document, selector, path)
    return value, {"selector": selector, "value": value}


def _resolve_python_projection(
    path: Path, relative: str, kind: str, selector: str, input_id: str
) -> tuple[Any, dict[str, Any]]:
    """Resolve one Python constant, symbol, or test selector."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise ContractError(f"cannot read authoritative Python source {relative}: {exc}") from exc
    if kind == "python_constant":
        value = _python_constant(text, path, selector)
        return value, {"selector": selector, "value": value}
    is_test = kind == "python_test"
    if is_test and not relative.startswith("tests/"):
        raise ContractError(f"python_test input {input_id} must resolve under tests/")
    value = _python_symbol_projection(text, path, selector, test=is_test)
    return value, value


def _resolve_input_projection(
    *, path: Path, relative: str, kind: str, selector: str, input_id: str
) -> tuple[Any, Any]:
    """Resolve the selected value and canonical digest projection for one input."""
    if kind == "json_schema":
        value = _mapping(load_json(path), f"authoritative schema {relative}")
        _validate_json_schema(value, f"authoritative schema {relative}")
        return value, value
    if kind in {"toml_project_field", "toml_project_script"}:
        return _resolve_toml_projection(path, relative, kind, selector)
    return _resolve_python_projection(path, relative, kind, selector, input_id)


def _resolve_input(root: Path, declaration: Mapping[str, Any]) -> ResolvedInput:
    """Resolve one registry input and produce its canonical projection digest."""
    input_id = _identifier(declaration.get("input_id"), "authoritative input input_id")
    kind = _string(declaration.get("kind"), f"authoritative input {input_id}.kind")
    if kind not in _INPUT_KINDS:
        raise ContractError(f"authoritative input {input_id} has unsupported kind {kind!r}")
    relative, path = _repo_relative_path(
        root, declaration.get("path"), f"authoritative input {input_id}.path"
    )
    selector = _string(declaration.get("selector"), f"authoritative input {input_id}.selector")
    value, projection = _resolve_input_projection(
        path=path,
        relative=relative,
        kind=kind,
        selector=selector,
        input_id=input_id,
    )
    expected = declaration.get("expected_value")
    if "expected_value" in declaration and value != expected:
        raise ContractError(
            f"authoritative input {input_id} resolved {value!r}, expected {expected!r}"
        )
    public = {
        "input_id": input_id,
        "kind": kind,
        "path": relative,
        "selector": selector,
        "sha256": sha256_bytes(canonical_bytes(projection)),
    }
    return ResolvedInput(public_record=public, value=value)


def _resolve_contract_input(
    *, input_id: str, kind: str, relative: str, path: Path, selector: str = "$"
) -> ResolvedInput:
    """Build one generator-owned control input record."""
    value = load_json(path)
    if kind == "json_schema":
        schema = _mapping(value, relative)
        _validate_json_schema(schema, relative)
    elif kind == "capability_registry":
        validate_registry(_mapping(value, relative))
    else:  # pragma: no cover - only generator-owned constants call this helper.
        raise ContractError(f"unsupported control input kind: {kind!r}")
    return ResolvedInput(
        public_record={
            "input_id": input_id,
            "kind": kind,
            "path": relative,
            "selector": selector,
            "sha256": sha256_bytes(canonical_bytes(value)),
        },
        value=value,
    )


def _validate_registry_input(declaration: Mapping[str, Any], index: int) -> str:
    """Validate one authoritative input declaration and return its ID."""
    label = f"registry.authoritative_inputs[{index}]"
    _assert_exact_keys(
        declaration,
        {"input_id", "kind", "path", "selector", "expected_value"},
        label,
    )
    input_id = _identifier(declaration.get("input_id"), f"{label}.input_id")
    kind = _string(declaration.get("kind"), f"{label}.kind")
    if kind not in _INPUT_KINDS:
        raise ContractError(f"{label}.kind is unsupported: {kind!r}")
    _string(declaration.get("path"), f"{label}.path")
    selector = _string(declaration.get("selector"), f"{label}.selector")
    if kind == "json_schema" and selector != "$":
        raise ContractError(f"{label}.selector must be '$' for a JSON schema")
    if "expected_value" in declaration and kind not in {
        "toml_project_script",
        "python_constant",
    }:
        raise ContractError(f"{label}.expected_value is unsupported for kind {kind!r}")
    if kind in {"toml_project_script", "python_constant"}:
        _string(declaration.get("expected_value"), f"{label}.expected_value")
    return input_id


def _validate_exit_codes(value: Any, label: str) -> None:
    """Validate ordered, unique command exit-code declarations."""
    rows = _sequence(value, label)
    if not rows:
        raise ContractError(f"{label} must not be empty")
    codes: list[int] = []
    for index, raw in enumerate(rows):
        row = _mapping(raw, f"{label}[{index}]")
        _assert_exact_keys(row, {"code", "meaning"}, f"{label}[{index}]")
        code = row.get("code")
        if not isinstance(code, int) or isinstance(code, bool) or not 0 <= code <= 255:
            raise ContractError(f"{label}[{index}].code must be an integer from 0 through 255")
        _identifier(row.get("meaning"), f"{label}[{index}].meaning")
        codes.append(code)
    if codes != sorted(set(codes)):
        raise ContractError(f"{label} must contain unique codes in ascending order")


def _capability_allowed_fields(kind: str) -> set[str]:
    """Return the exact registry fields allowed for one capability kind."""
    common = {
        "capability_id",
        "kind",
        "interface_version",
        "status",
        "semantics_id",
        "location",
        "authority",
        "deprecation",
    }
    kind_fields = {
        "cli": {"entrypoint_input_id", "argv", "exit_codes"},
        "schema": set(),
        "protocol": {"identifier_input_id"},
        "artifact_identity": {"convention_identifier"},
    }[kind]
    return common | kind_fields


def _validate_capability_authority(
    capability: Mapping[str, Any],
    *,
    label: str,
    inputs: Mapping[str, Mapping[str, Any]],
) -> tuple[str, list[str]]:
    """Validate capability location and authoritative input references."""
    location = _string(capability.get("location"), f"{label}.location")
    authority = _sequence(capability.get("authority"), f"{label}.authority")
    authority_ids = [_identifier(item, f"{label}.authority") for item in authority]
    if not authority_ids or len(authority_ids) != len(set(authority_ids)):
        raise ContractError(f"{label}.authority must contain unique input IDs")
    missing = sorted(set(authority_ids) - set(inputs))
    if missing:
        raise ContractError(f"{label}.authority references unknown input(s): {', '.join(missing)}")
    authority_paths = {str(inputs[item].get("path")) for item in authority_ids}
    if location not in authority_paths:
        raise ContractError(f"{label}.location must be one of its authoritative input paths")
    return location, authority_ids


def _validate_cli_registry_capability(
    capability: Mapping[str, Any],
    *,
    label: str,
    inputs: Mapping[str, Mapping[str, Any]],
    authority_ids: list[str],
) -> None:
    """Validate CLI-specific authority and exit-code declarations."""
    entrypoint_id = _identifier(
        capability.get("entrypoint_input_id"), f"{label}.entrypoint_input_id"
    )
    if entrypoint_id not in authority_ids:
        raise ContractError(f"{label}.entrypoint_input_id must be listed in authority")
    if inputs[entrypoint_id].get("kind") != "toml_project_script":
        raise ContractError(f"{label}.entrypoint_input_id must select a project script")
    argv = _sequence(capability.get("argv"), f"{label}.argv")
    if not argv or any(not isinstance(item, str) or not item for item in argv):
        raise ContractError(f"{label}.argv must contain non-empty strings")
    _validate_exit_codes(capability.get("exit_codes"), f"{label}.exit_codes")
    if not any(inputs[item].get("kind") == "python_test" for item in authority_ids):
        raise ContractError(f"{label} must cite a tested CLI contract")


def _validate_schema_registry_capability(
    *,
    label: str,
    location: str,
    inputs: Mapping[str, Mapping[str, Any]],
    authority_ids: list[str],
) -> None:
    """Validate schema-specific authority declarations."""
    schema_inputs = [item for item in authority_ids if inputs[item].get("kind") == "json_schema"]
    if len(schema_inputs) != 1 or inputs[schema_inputs[0]].get("path") != location:
        raise ContractError(f"{label} must cite exactly one location-matching JSON schema")


def _validate_protocol_registry_capability(
    capability: Mapping[str, Any],
    *,
    label: str,
    inputs: Mapping[str, Mapping[str, Any]],
    authority_ids: list[str],
) -> None:
    """Validate protocol identifier authority."""
    identifier_id = _identifier(
        capability.get("identifier_input_id"), f"{label}.identifier_input_id"
    )
    if identifier_id not in authority_ids:
        raise ContractError(f"{label}.identifier_input_id must be listed in authority")
    if inputs[identifier_id].get("kind") != "python_constant":
        raise ContractError(f"{label}.identifier_input_id must select a Python constant")


def _validate_registry_deprecation(
    capability: Mapping[str, Any], *, label: str, status: str
) -> None:
    """Validate the status/deprecation-record relationship."""
    deprecation = capability.get("deprecation")
    if status != "deprecated":
        if deprecation is not None:
            raise ContractError(f"{label}.deprecation is allowed only for deprecated capabilities")
        return
    record = _mapping(deprecation, f"{label}.deprecation")
    _assert_exact_keys(
        record,
        {"reason_code", "replacement_capability_id", "removal_contract_version"},
        f"{label}.deprecation",
    )
    _identifier(record.get("reason_code"), f"{label}.deprecation.reason_code")
    _semver(
        record.get("removal_contract_version"),
        f"{label}.deprecation.removal_contract_version",
    )
    if "replacement_capability_id" in record:
        _identifier(
            record["replacement_capability_id"],
            f"{label}.deprecation.replacement_capability_id",
        )


def _validate_registry_capability(
    capability: Mapping[str, Any], index: int, inputs: Mapping[str, Mapping[str, Any]]
) -> str:
    """Validate one capability declaration and return its capability ID."""
    label = f"registry.capabilities[{index}]"
    kind = _string(capability.get("kind"), f"{label}.kind")
    if kind not in _CAPABILITY_KINDS:
        raise ContractError(f"{label}.kind is unsupported: {kind!r}")
    _assert_exact_keys(capability, _capability_allowed_fields(kind), label)
    capability_id = _identifier(capability.get("capability_id"), f"{label}.capability_id")
    _semver(capability.get("interface_version"), f"{label}.interface_version")
    status = _string(capability.get("status"), f"{label}.status")
    if status not in _STATUSES:
        raise ContractError(f"{label}.status is unsupported: {status!r}")
    if status == "stable":
        raise ContractError(
            f"{label} cannot mark {capability_id!r} stable without a separate reviewed stability owner"
        )
    _identifier(capability.get("semantics_id"), f"{label}.semantics_id")
    location, authority_ids = _validate_capability_authority(capability, label=label, inputs=inputs)
    if kind == "cli":
        _validate_cli_registry_capability(
            capability, label=label, inputs=inputs, authority_ids=authority_ids
        )
    elif kind == "schema":
        _validate_schema_registry_capability(
            label=label, location=location, inputs=inputs, authority_ids=authority_ids
        )
    elif kind == "protocol":
        _validate_protocol_registry_capability(
            capability, label=label, inputs=inputs, authority_ids=authority_ids
        )
    else:
        _identifier(capability.get("convention_identifier"), f"{label}.convention_identifier")
    _validate_registry_deprecation(capability, label=label, status=status)
    return capability_id


def _validate_registry_header(registry: Mapping[str, Any]) -> str:
    """Validate registry identity, producer, and change metadata."""
    if registry.get("registry_schema_version") != REGISTRY_SCHEMA_VERSION:
        raise ContractError(
            f"registry_schema_version must be {REGISTRY_SCHEMA_VERSION!r}, "
            f"got {registry.get('registry_schema_version')!r}"
        )
    _semver(registry.get("contract_version"), "registry.contract_version")
    producer = _mapping(registry.get("producer"), "registry.producer")
    _assert_exact_keys(
        producer,
        {"producer_id", "repository_url", "supported_python_input_id"},
        "registry.producer",
    )
    if (
        producer.get("producer_id") != "robot_sf"
        or producer.get("repository_url") != REPOSITORY_URL
    ):
        raise ContractError("registry.producer must identify the public Robot SF repository")
    python_input_id = _identifier(
        producer.get("supported_python_input_id"), "registry.producer.supported_python_input_id"
    )
    change = _mapping(registry.get("change"), "registry.change")
    _assert_exact_keys(change, {"declared_type", "based_on_contract_digest"}, "registry.change")
    if change.get("declared_type") not in {"initial", "additive", "deprecated", "breaking"}:
        raise ContractError("registry.change.declared_type is unsupported")
    based_on = change.get("based_on_contract_digest")
    if change.get("declared_type") == "initial":
        if based_on is not None:
            raise ContractError("an initial registry change must use a null base digest")
    elif not isinstance(based_on, str) or _SHA256_RE.fullmatch(based_on) is None:
        raise ContractError("a non-initial registry change requires a SHA-256 base digest")
    return python_input_id


def _index_registry_inputs(registry: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Validate and index authoritative input declarations."""
    input_rows = _sequence(registry.get("authoritative_inputs"), "registry.authoritative_inputs")
    inputs: dict[str, dict[str, Any]] = {}
    for index, raw in enumerate(input_rows):
        declaration = _mapping(raw, f"registry.authoritative_inputs[{index}]")
        input_id = _validate_registry_input(declaration, index)
        if input_id in inputs or input_id in _CONTROL_INPUT_IDS:
            raise ContractError(f"duplicate or reserved authoritative input ID: {input_id}")
        inputs[input_id] = declaration
    return inputs


def _validate_registry_capabilities(
    registry: Mapping[str, Any],
    inputs: Mapping[str, Mapping[str, Any]],
    python_input_id: str,
) -> None:
    """Validate capability declarations and complete input coverage."""
    if python_input_id not in inputs or inputs[python_input_id].get("kind") != "toml_project_field":
        raise ContractError("supported_python_input_id must select a TOML project field")
    capability_rows = _sequence(registry.get("capabilities"), "registry.capabilities")
    if not capability_rows:
        raise ContractError("registry.capabilities must not be empty")
    capability_ids: set[str] = set()
    used_inputs = {python_input_id}
    for index, raw in enumerate(capability_rows):
        capability = _mapping(raw, f"registry.capabilities[{index}]")
        capability_id = _validate_registry_capability(capability, index, inputs)
        if capability_id in capability_ids:
            raise ContractError(f"duplicate capability ID: {capability_id}")
        capability_ids.add(capability_id)
        used_inputs.update(str(item) for item in capability["authority"])
    unused = sorted(set(inputs) - used_inputs)
    if unused:
        raise ContractError(f"registry has unused authoritative input(s): {', '.join(unused)}")


def _validate_registry_fixtures(registry: Mapping[str, Any]) -> None:
    """Validate optional canonical public fixture declarations."""
    fixtures = _sequence(
        registry.get("canonical_public_fixtures"), "registry.canonical_public_fixtures"
    )
    fixture_ids: set[str] = set()
    for index, raw in enumerate(fixtures):
        fixture = _mapping(raw, f"registry.canonical_public_fixtures[{index}]")
        _assert_exact_keys(
            fixture,
            {"fixture_id", "fixture_version", "path"},
            f"canonical fixture {index}",
        )
        fixture_id = _identifier(fixture.get("fixture_id"), f"canonical fixture {index}.fixture_id")
        if fixture_id in fixture_ids:
            raise ContractError(f"duplicate canonical fixture ID: {fixture_id}")
        fixture_ids.add(fixture_id)
        _semver(fixture.get("fixture_version"), f"canonical fixture {index}.fixture_version")
        _string(fixture.get("path"), f"canonical fixture {index}.path")


def validate_registry(registry: Mapping[str, Any]) -> None:
    """Validate the explicit capability registry before source resolution."""
    _assert_exact_keys(
        registry,
        {
            "registry_schema_version",
            "contract_version",
            "producer",
            "change",
            "authoritative_inputs",
            "capabilities",
            "canonical_public_fixtures",
        },
        "registry",
    )
    python_input_id = _validate_registry_header(registry)
    inputs = _index_registry_inputs(registry)
    _validate_registry_capabilities(registry, inputs, python_input_id)
    _validate_registry_fixtures(registry)


def _build_capability(
    declaration: Mapping[str, Any], resolved: Mapping[str, ResolvedInput]
) -> dict[str, Any]:
    """Build one public capability record from a validated declaration."""
    kind = str(declaration["kind"])
    authority = sorted(str(item) for item in declaration["authority"])
    record: dict[str, Any] = {
        "capability_id": declaration["capability_id"],
        "kind": kind,
        "interface_version": declaration["interface_version"],
        "status": declaration["status"],
        "semantics_id": declaration["semantics_id"],
        "location": declaration["location"],
        "authority": authority,
    }
    if kind == "schema":
        schema_inputs = [
            item for item in authority if resolved[item].public_record["kind"] == "json_schema"
        ]
        schema = _mapping(
            resolved[schema_inputs[0]].value, f"schema capability {record['capability_id']}"
        )
        record["schema_id"] = schema["$id"]
        record["json_schema_draft"] = schema["$schema"]
    elif kind == "cli":
        entrypoint_id = str(declaration["entrypoint_input_id"])
        record["command"] = {
            "entrypoint": resolved[entrypoint_id].public_record["selector"],
            "entrypoint_target": resolved[entrypoint_id].value,
            "argv": list(declaration["argv"]),
            "exit_codes": [dict(item) for item in declaration["exit_codes"]],
        }
    elif kind == "protocol":
        record["protocol_identifier"] = resolved[str(declaration["identifier_input_id"])].value
    else:
        record["convention_identifier"] = declaration["convention_identifier"]
    if "deprecation" in declaration:
        record["deprecation"] = dict(declaration["deprecation"])
    return record


def _build_fixture_records(root: Path, registry: Mapping[str, Any]) -> list[dict[str, str]]:
    """Resolve fixture locations without hashing mutable fixture contents.

    The producer contract declares a stable fixture identity, version, and
    location. It must not hash the fixture itself: the fixture records this
    contract digest, so hashing the fixture here would create a digest cycle.
    Release manifests bind both content digests later.
    """
    records: list[dict[str, str]] = []
    for index, raw in enumerate(registry["canonical_public_fixtures"]):
        declaration = _mapping(raw, f"canonical fixture {index}")
        relative, _path = _repo_relative_path(
            root, declaration["path"], f"canonical fixture {index}.path"
        )
        records.append(
            {
                "fixture_id": str(declaration["fixture_id"]),
                "fixture_version": str(declaration["fixture_version"]),
                "path": relative,
            }
        )
    return sorted(records, key=lambda item: item["fixture_id"])


def build_contract(
    *,
    root: Path,
    registry_path: Path = DEFAULT_REGISTRY_PATH,
    schema_path: Path = DEFAULT_CONTRACT_SCHEMA_PATH,
) -> dict[str, Any]:
    """Build the revision-invariant producer contract from authoritative sources."""
    root = root.resolve()
    registry_relative, registry_file = _root_relative_existing_path(
        root, registry_path, "capability registry path"
    )
    schema_relative, schema_file = _root_relative_existing_path(
        root, schema_path, "ecosystem contract schema path"
    )
    registry = _mapping(load_json(registry_file), "capability registry")
    validate_registry(registry)
    contract_schema = _load_schema(schema_file, "ecosystem contract schema")

    resolved: dict[str, ResolvedInput] = {
        "contract.capability_registry.v1": _resolve_contract_input(
            input_id="contract.capability_registry.v1",
            kind="capability_registry",
            relative=registry_relative,
            path=registry_file,
        ),
        "contract.schema.v1": _resolve_contract_input(
            input_id="contract.schema.v1",
            kind="json_schema",
            relative=schema_relative,
            path=schema_file,
        ),
    }
    for raw in registry["authoritative_inputs"]:
        declaration = _mapping(raw, "authoritative input")
        item = _resolve_input(root, declaration)
        resolved[str(item.public_record["input_id"])] = item

    producer = _mapping(registry["producer"], "registry.producer")
    supported_python = resolved[str(producer["supported_python_input_id"])].value
    if not isinstance(supported_python, str) or not supported_python:
        raise ContractError("supported Python selector did not resolve to a non-empty string")
    capabilities = sorted(
        (
            _build_capability(_mapping(item, "capability"), resolved)
            for item in registry["capabilities"]
        ),
        key=lambda item: item["capability_id"],
    )
    contract: dict[str, Any] = {
        "schema_version": CONTRACT_SCHEMA_VERSION,
        "contract_version": registry["contract_version"],
        "producer": {
            "producer_id": producer["producer_id"],
            "repository_url": producer["repository_url"],
            "supported_python": supported_python,
        },
        "canonicalization": {
            "profile": CANONICALIZATION_PROFILE,
            "hash_algorithm": "sha256",
            "trailing_lf": False,
        },
        "change": dict(registry["change"]),
        "compatibility_policy": dict(COMPATIBILITY_POLICY),
        "minimum_consumer_features": sorted(MINIMUM_CONSUMER_FEATURES),
        "revision_envelope_schema_version": REVISION_ENVELOPE_SCHEMA_VERSION,
        "authoritative_inputs": sorted(
            (item.public_record for item in resolved.values()), key=lambda item: item["input_id"]
        ),
        "capabilities": capabilities,
        "canonical_public_fixtures": _build_fixture_records(root, registry),
    }
    contract["contract_digest"] = {
        "algorithm": "sha256",
        "scope": "canonical_document_without_contract_digest",
        "value": sha256_bytes(canonical_bytes(contract)),
    }
    validate_contract_document(contract, schema=contract_schema, root=root, verify_sources=True)
    return contract


def _contract_digest_value(contract: Mapping[str, Any]) -> str:
    """Recompute the scoped digest of a contract document."""
    unsigned = dict(contract)
    unsigned.pop("contract_digest", None)
    return sha256_bytes(canonical_bytes(unsigned))


def _resolve_public_input(root: Path, record: Mapping[str, Any]) -> ResolvedInput:
    """Re-resolve a generated input record for stale-source detection."""
    declaration: dict[str, Any] = {
        "input_id": record.get("input_id"),
        "kind": record.get("kind"),
        "path": record.get("path"),
        "selector": record.get("selector"),
    }
    kind = record.get("kind")
    if kind == "capability_registry":
        relative, path = _repo_relative_path(root, record.get("path"), "capability registry path")
        return _resolve_contract_input(
            input_id=str(record.get("input_id")),
            kind="capability_registry",
            relative=relative,
            path=path,
        )
    return _resolve_input(root, declaration)


def _assert_sorted_unique(values: list[str], label: str) -> None:
    """Require a list of strings to be unique and lexicographically sorted."""
    if values != sorted(set(values)):
        raise ContractError(f"{label} must be unique and sorted")


def _validate_contract_identity(contract: Mapping[str, Any]) -> None:
    """Validate supported schema identity, scoped digest, and base binding."""
    if contract.get("schema_version") != CONTRACT_SCHEMA_VERSION:
        raise ContractError(
            f"unsupported contract schema version: {contract.get('schema_version')!r}"
        )
    expected_digest = _contract_digest_value(contract)
    digest = _mapping(contract.get("contract_digest"), "contract_digest")
    if digest.get("value") != expected_digest:
        raise ContractError(
            f"stale contract_digest: expected {expected_digest}, got {digest.get('value')!r}"
        )
    change = _mapping(contract.get("change"), "change")
    is_initial = change.get("declared_type") == "initial"
    base_digest = change.get("based_on_contract_digest")
    if is_initial and base_digest is not None:
        raise ContractError("an initial contract must use a null based_on_contract_digest")
    if not is_initial and not isinstance(base_digest, str):
        raise ContractError("a non-initial contract must name its base digest")


def _index_contract_inputs(
    contract: Mapping[str, Any],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Validate deterministic input ordering and return rows plus an index."""
    rows = [_mapping(item, "authoritative input") for item in contract["authoritative_inputs"]]
    input_ids = [str(item["input_id"]) for item in rows]
    _assert_sorted_unique(input_ids, "authoritative input IDs")
    for item in rows:
        _normalized_repo_path(item["path"], f"authoritative input {item['input_id']} path")
    return rows, {str(item["input_id"]): item for item in rows}


def _validate_contract_capability(capability: Mapping[str, Any], inputs: Mapping[str, Any]) -> None:
    """Validate one capability's references, status, and CLI exit ordering."""
    capability_id = str(capability["capability_id"])
    _normalized_repo_path(capability["location"], f"capability {capability_id} location")
    authority = [str(item) for item in capability["authority"]]
    _assert_sorted_unique(authority, f"capability {capability_id} authority")
    missing = sorted(set(authority) - set(inputs))
    if missing:
        raise ContractError(
            f"capability {capability_id} references unknown authoritative input(s): "
            f"{', '.join(missing)}"
        )
    is_deprecated = capability["status"] == "deprecated"
    has_record = "deprecation" in capability
    if is_deprecated and not has_record:
        raise ContractError(f"deprecated capability {capability_id} lacks a deprecation record")
    if not is_deprecated and has_record:
        raise ContractError(f"non-deprecated capability {capability_id} has a deprecation record")
    if capability["kind"] == "cli":
        codes = [int(item["code"]) for item in capability["command"]["exit_codes"]]
        if codes != sorted(set(codes)):
            raise ContractError(f"capability {capability_id} exit codes are not unique and sorted")


def _validate_contract_capabilities(contract: Mapping[str, Any], inputs: Mapping[str, Any]) -> None:
    """Validate deterministic capability ordering and each capability record."""
    rows = [_mapping(item, "capability") for item in contract["capabilities"]]
    capability_ids = [str(item["capability_id"]) for item in rows]
    _assert_sorted_unique(capability_ids, "capability IDs")
    for capability in rows:
        _validate_contract_capability(capability, inputs)


def _contract_fixture_rows(contract: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Validate canonical fixture and consumer-feature ordering."""
    rows = [_mapping(item, "canonical fixture") for item in contract["canonical_public_fixtures"]]
    fixture_ids = [str(item["fixture_id"]) for item in rows]
    _assert_sorted_unique(fixture_ids, "canonical fixture IDs")
    for item in rows:
        _semver(item.get("fixture_version"), f"canonical fixture {item['fixture_id']} version")
        _normalized_repo_path(item["path"], f"canonical fixture {item['fixture_id']} path")
    features = [str(item) for item in contract["minimum_consumer_features"]]
    _assert_sorted_unique(features, "minimum consumer features")
    return rows


def _verify_contract_sources(
    *,
    root: Path,
    input_rows: Sequence[Mapping[str, Any]],
    fixture_rows: Sequence[Mapping[str, Any]],
) -> None:
    """Re-resolve authoritative inputs and fixture locations."""
    for record in input_rows:
        resolved = _resolve_public_input(root, record)
        actual = resolved.public_record["sha256"]
        if record["sha256"] != actual:
            raise ContractError(
                f"stale authoritative input digest for {record['input_id']}: "
                f"expected {actual}, got {record['sha256']}"
            )
    for fixture in fixture_rows:
        _relative, _path = _repo_relative_path(
            root, fixture["path"], f"canonical fixture {fixture['fixture_id']}"
        )


def validate_contract_document(
    contract: Mapping[str, Any],
    *,
    schema: Mapping[str, Any],
    root: Path | None = None,
    verify_sources: bool = False,
) -> None:
    """Validate schema, digest, ordering, references, and optional live sources."""
    _validate_against_schema(contract, schema, "ecosystem contract")
    _validate_contract_identity(contract)
    input_rows, inputs = _index_contract_inputs(contract)
    _validate_contract_capabilities(contract, inputs)
    fixture_rows = _contract_fixture_rows(contract)
    if not verify_sources:
        return
    if root is None:
        raise ContractError("verify_sources requires a repository root")
    _verify_contract_sources(root=root.resolve(), input_rows=input_rows, fixture_rows=fixture_rows)


def _parse_digest_sidecar(path: Path) -> tuple[str, str]:
    """Parse one strict sha256sum-compatible sidecar line."""
    try:
        text = path.read_text(encoding="ascii")
    except (OSError, UnicodeError) as exc:
        raise ContractError(f"cannot read digest sidecar {path}: {exc}") from exc
    match = re.fullmatch(r"([0-9a-f]{64})  ([^\n]+)\n", text)
    if match is None:
        raise ContractError(f"digest sidecar {path} must contain one sha256sum-compatible line")
    return match.group(1), match.group(2)


def validate_contract_path(
    path: Path,
    *,
    schema_path: Path,
    root: Path,
    digest_path: Path | None = None,
    verify_sources: bool = False,
) -> dict[str, Any]:
    """Validate one canonical contract file and optional exact-byte sidecar."""
    contract = _mapping(load_json(path), f"ecosystem contract {path}")
    schema = _load_schema(schema_path, "ecosystem contract schema")
    validate_contract_document(contract, schema=schema, root=root, verify_sources=verify_sources)
    raw = path.read_bytes()
    canonical = canonical_bytes(contract)
    if raw != canonical:
        raise ContractError(f"contract {path} is valid JSON but is not canonical RFC 8785 bytes")
    if digest_path is not None:
        digest, filename = _parse_digest_sidecar(digest_path)
        if filename != path.name:
            raise ContractError(
                f"digest sidecar names {filename!r}, expected contract filename {path.name!r}"
            )
        actual = sha256_bytes(raw)
        if digest != actual:
            raise ContractError(f"stale contract sidecar digest: expected {actual}, got {digest}")
    return contract


def _sidecar_bytes(contract_path: Path, contract_bytes: bytes) -> bytes:
    """Return the deterministic sha256sum sidecar bytes for a contract."""
    return f"{sha256_bytes(contract_bytes)}  {contract_path.name}\n".encode("ascii")


def write_contract(
    *,
    root: Path,
    registry_path: Path,
    schema_path: Path,
    output_path: Path,
    digest_path: Path,
) -> dict[str, Any]:
    """Generate and write the canonical contract and its exact-byte digest."""
    contract = build_contract(root=root, registry_path=registry_path, schema_path=schema_path)
    output = _path_argument(root, output_path)
    digest_output = _path_argument(root, digest_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    digest_output.parent.mkdir(parents=True, exist_ok=True)
    payload = canonical_bytes(contract)
    output.write_bytes(payload)
    digest_output.write_bytes(_sidecar_bytes(output, payload))
    validate_contract_path(
        output,
        schema_path=_path_argument(root, schema_path),
        root=root,
        digest_path=digest_output,
        verify_sources=True,
    )
    return contract


def check_contract(
    *,
    root: Path,
    registry_path: Path,
    schema_path: Path,
    output_path: Path,
    digest_path: Path,
) -> dict[str, Any]:
    """Fail when committed contract bytes or input digests are stale."""
    output = _path_argument(root, output_path)
    digest_output = _path_argument(root, digest_path)
    if not output.is_file():
        raise ContractDriftError(f"committed contract is missing: {output}")
    if not digest_output.is_file():
        raise ContractDriftError(f"committed contract digest is missing: {digest_output}")
    expected = build_contract(root=root, registry_path=registry_path, schema_path=schema_path)
    expected_bytes = canonical_bytes(expected)
    actual_bytes = output.read_bytes()
    if actual_bytes != expected_bytes:
        try:
            validate_contract_path(
                output,
                schema_path=_path_argument(root, schema_path),
                root=root,
                digest_path=digest_output,
                verify_sources=True,
            )
        except ContractError as exc:
            raise ContractDriftError(str(exc)) from exc
        raise ContractDriftError(
            "committed contract differs from the authoritative generated contract"
        )
    expected_sidecar = _sidecar_bytes(output, expected_bytes)
    if digest_output.read_bytes() != expected_sidecar:
        raise ContractDriftError("committed contract SHA-256 sidecar is stale")
    validate_contract_path(
        output,
        schema_path=_path_argument(root, schema_path),
        root=root,
        digest_path=digest_output,
        verify_sources=True,
    )
    return expected


def validate_requirements(requirements: Mapping[str, Any]) -> None:
    """Validate the dependency-free downstream requirements document shape."""
    _assert_exact_keys(
        requirements,
        {
            "schema_version",
            "supported_contract_schema_majors",
            "supported_consumer_features",
            "required_capabilities",
        },
        "requirements",
    )
    if requirements.get("schema_version") != REQUIREMENTS_SCHEMA_VERSION:
        raise ContractError(f"requirements.schema_version must be {REQUIREMENTS_SCHEMA_VERSION!r}")
    majors = _sequence(
        requirements.get("supported_contract_schema_majors"),
        "requirements.supported_contract_schema_majors",
    )
    if not majors or any(
        not isinstance(item, int) or isinstance(item, bool) or item < 0 for item in majors
    ):
        raise ContractError("supported_contract_schema_majors must contain non-negative integers")
    if majors != sorted(set(majors)):
        raise ContractError("supported_contract_schema_majors must be unique and sorted")
    features = _sequence(
        requirements.get("supported_consumer_features"),
        "requirements.supported_consumer_features",
    )
    feature_ids = [_identifier(item, "supported consumer feature") for item in features]
    _assert_sorted_unique(feature_ids, "supported consumer features")
    rows = _sequence(
        requirements.get("required_capabilities"), "requirements.required_capabilities"
    )
    capability_ids: list[str] = []
    for index, raw in enumerate(rows):
        requirement = _mapping(raw, f"required_capabilities[{index}]")
        _assert_exact_keys(
            requirement,
            {"capability_id", "interface_major", "accepted_statuses", "semantics_id"},
            f"required_capabilities[{index}]",
        )
        capability_ids.append(
            _identifier(
                requirement.get("capability_id"), f"required_capabilities[{index}].capability_id"
            )
        )
        major = requirement.get("interface_major")
        if not isinstance(major, int) or isinstance(major, bool) or major < 0:
            raise ContractError(
                f"required_capabilities[{index}].interface_major must be non-negative"
            )
        statuses = _sequence(
            requirement.get("accepted_statuses"),
            f"required_capabilities[{index}].accepted_statuses",
        )
        if not statuses or any(item not in _STATUSES for item in statuses):
            raise ContractError(f"required_capabilities[{index}].accepted_statuses is invalid")
        if statuses != sorted(set(statuses)):
            raise ContractError(
                f"required_capabilities[{index}].accepted_statuses must be unique and sorted"
            )
        _identifier(requirement.get("semantics_id"), f"required_capabilities[{index}].semantics_id")
    _assert_sorted_unique(capability_ids, "required capability IDs")


def check_compatibility(
    contract: Mapping[str, Any],
    requirements: Mapping[str, Any],
    *,
    schema: Mapping[str, Any],
) -> dict[str, Any]:
    """Compare a producer contract against explicit downstream requirements."""
    validate_contract_document(contract, schema=schema)
    validate_requirements(requirements)
    errors: list[str] = []
    warnings: list[str] = []
    matched: list[str] = []
    if 1 not in requirements["supported_contract_schema_majors"]:
        errors.append("consumer does not support ecosystem contract schema major 1")
    missing_features = sorted(
        set(contract["minimum_consumer_features"])
        - set(requirements["supported_consumer_features"])
    )
    for feature in missing_features:
        errors.append(f"consumer lacks required validator feature {feature}")
    capabilities = {item["capability_id"]: item for item in contract["capabilities"]}
    for requirement in requirements["required_capabilities"]:
        capability_id = requirement["capability_id"]
        error_count = len(errors)
        capability = capabilities.get(capability_id)
        if capability is None:
            errors.append(f"required capability is missing: {capability_id}")
            continue
        major = _semver(capability["interface_version"], f"{capability_id}.interface_version")[0]
        if major != requirement["interface_major"]:
            errors.append(
                f"{capability_id} has interface major {major}, required "
                f"{requirement['interface_major']}"
            )
        if capability["status"] not in requirement["accepted_statuses"]:
            errors.append(
                f"{capability_id} has status {capability['status']!r}, accepted statuses are "
                f"{requirement['accepted_statuses']!r}"
            )
        if capability["semantics_id"] != requirement["semantics_id"]:
            errors.append(
                f"{capability_id} has semantics {capability['semantics_id']!r}, required "
                f"{requirement['semantics_id']!r}"
            )
        if capability["status"] == "deprecated":
            warnings.append(f"required capability is deprecated: {capability_id}")
        if len(errors) == error_count:
            matched.append(capability_id)
    return {
        "schema_version": COMPATIBILITY_REPORT_SCHEMA_VERSION,
        "compatible": not errors,
        "errors": errors,
        "warnings": warnings,
        "matched_capability_ids": sorted(matched),
    }


def _authority_digest_signature(
    contract: Mapping[str, Any], capability: Mapping[str, Any]
) -> tuple[tuple[str, str], ...]:
    """Return per-capability authoritative input digests for change detection."""
    inputs = {item["input_id"]: item["sha256"] for item in contract["authoritative_inputs"]}
    return tuple((item, inputs[item]) for item in capability["authority"])


def _classify_interface_version(
    capability_id: str, old: Mapping[str, Any], new: Mapping[str, Any]
) -> tuple[list[str], list[str]]:
    """Classify interface identity and version changes for one capability."""
    breaking: list[str] = []
    additive: list[str] = []
    old_version = _semver(old["interface_version"], f"{capability_id}.interface_version")
    new_version = _semver(new["interface_version"], f"{capability_id}.interface_version")
    if new["kind"] != old["kind"]:
        breaking.append(f"changed kind for {capability_id}")
    if new_version[0] != old_version[0]:
        breaking.append(f"changed interface major for {capability_id}")
    elif new_version < old_version:
        breaking.append(f"decreased interface version for {capability_id}")
    elif new_version > old_version:
        additive.append(f"increased same-major interface version for {capability_id}")
    if new["semantics_id"] != old["semantics_id"]:
        breaking.append(f"changed semantics ID for {capability_id}")
    if old["kind"] == "cli" and new.get("command") != old.get("command"):
        breaking.append(f"changed command or exit semantics for {capability_id}")
    for field in ("schema_id", "protocol_identifier", "convention_identifier"):
        if old.get(field) != new.get(field):
            breaking.append(f"changed {field} for {capability_id}")
    return breaking, additive


def _classify_status(
    capability_id: str, old: Mapping[str, Any], new: Mapping[str, Any]
) -> tuple[list[str], list[str], list[str]]:
    """Classify status transitions for one capability."""
    breaking: list[str] = []
    deprecated: list[str] = []
    additive: list[str] = []
    if new["status"] == "deprecated" and old["status"] != "deprecated":
        deprecated.append(f"deprecated capability {capability_id}")
    elif old["status"] != new["status"]:
        breaking.append(f"changed status for {capability_id}: {old['status']} -> {new['status']}")
    return breaking, deprecated, additive


def _classify_existing_capability(
    capability_id: str,
    old: Mapping[str, Any],
    new: Mapping[str, Any],
    baseline: Mapping[str, Any],
    candidate: Mapping[str, Any],
) -> tuple[list[str], list[str], list[str]]:
    """Classify all compatibility-visible changes for one existing capability."""
    breaking, additive = _classify_interface_version(capability_id, old, new)
    status_breaking, deprecated, status_additive = _classify_status(capability_id, old, new)
    breaking.extend(status_breaking)
    additive.extend(status_additive)
    authority_changed = _authority_digest_signature(baseline, old) != _authority_digest_signature(
        candidate, new
    )
    if authority_changed:
        breaking.append(
            f"changed authoritative inputs for {capability_id}; v1 requires explicit review "
            "and treats source changes as breaking"
        )
    if (
        old["status"] == "deprecated"
        and new["status"] == "deprecated"
        and old.get("deprecation") != new.get("deprecation")
    ):
        breaking.append(f"changed deprecation semantics for {capability_id}")
    return breaking, deprecated, additive


def classify_contract_change(
    baseline: Mapping[str, Any], candidate: Mapping[str, Any]
) -> tuple[str, list[str]]:
    """Classify compatibility-visible changes between two valid contracts."""
    baseline_caps = {item["capability_id"]: item for item in baseline["capabilities"]}
    candidate_caps = {item["capability_id"]: item for item in candidate["capabilities"]}
    breaking: list[str] = []
    deprecated: list[str] = []
    additive: list[str] = []
    baseline_features = set(baseline["minimum_consumer_features"])
    candidate_features = set(candidate["minimum_consumer_features"])
    for feature in sorted(candidate_features - baseline_features):
        breaking.append(
            f"added required consumer feature {feature}; existing consumers may reject the contract"
        )
    for capability_id in sorted(set(baseline_caps) - set(candidate_caps)):
        breaking.append(f"removed capability {capability_id}")
    for capability_id in sorted(set(candidate_caps) - set(baseline_caps)):
        additive.append(f"added capability {capability_id}")
    for capability_id in sorted(set(baseline_caps) & set(candidate_caps)):
        old = baseline_caps[capability_id]
        new = candidate_caps[capability_id]
        cap_breaking, cap_deprecated, cap_additive = _classify_existing_capability(
            capability_id, old, new, baseline, candidate
        )
        breaking.extend(cap_breaking)
        deprecated.extend(cap_deprecated)
        additive.extend(cap_additive)
    if breaking:
        return "breaking", sorted(set(breaking + deprecated + additive))
    if deprecated:
        return "deprecated", sorted(set(deprecated + additive))
    if additive:
        return "additive", sorted(set(additive))
    return "unchanged", []


def check_declared_change(
    baseline: Mapping[str, Any],
    candidate: Mapping[str, Any],
    *,
    schema: Mapping[str, Any],
) -> dict[str, Any]:
    """Validate change classification, base binding, and contract-major transition."""
    validate_contract_document(baseline, schema=schema)
    validate_contract_document(candidate, schema=schema)
    actual, reasons = classify_contract_change(baseline, candidate)
    declared = candidate["change"]["declared_type"]
    errors: list[str] = []
    if candidate["change"]["based_on_contract_digest"] != baseline["contract_digest"]["value"]:
        errors.append("candidate based_on_contract_digest does not bind the baseline contract")
    if declared != actual:
        errors.append(f"candidate declares {declared!r}, but the detected change is {actual!r}")
    baseline_major = _semver(baseline["contract_version"], "baseline.contract_version")[0]
    baseline_version = _semver(baseline["contract_version"], "baseline.contract_version")
    candidate_version = _semver(candidate["contract_version"], "candidate.contract_version")
    candidate_major = candidate_version[0]
    if declared != "initial" and candidate_version <= baseline_version:
        errors.append("non-initial candidate contract_version must be greater than the baseline")
    if actual == "breaking" and candidate_major <= baseline_major:
        errors.append("breaking changes require a new contract major")
    if actual in {"additive", "deprecated", "unchanged"} and candidate_major != baseline_major:
        errors.append(f"{actual} changes must preserve the contract major")
    return {
        "schema_version": CHANGE_REPORT_SCHEMA_VERSION,
        "valid": not errors,
        "declared_change": declared,
        "detected_change": actual,
        "reasons": reasons,
        "errors": errors,
    }


def build_revision_envelope(
    *,
    root: Path,
    contract_path: Path,
    contract_schema_path: Path,
    revision_schema_path: Path,
    lock_path: Path,
    source_commit: str,
    release_status: str,
    release_tag: str | None,
) -> dict[str, Any]:
    """Build a deterministic revision envelope for release assembly."""
    if re.fullmatch(r"[0-9a-f]{40}", source_commit) is None:
        raise ContractError("source_commit must be a full lowercase 40-character Git SHA")
    if release_status not in {"unreleased", "tagged", "released"}:
        raise ContractError(f"unsupported release_status: {release_status!r}")
    if release_status == "unreleased" and release_tag is not None:
        raise ContractError("an unreleased revision envelope must not include a release tag")
    if release_status in {"tagged", "released"} and not release_tag:
        raise ContractError(f"release_status {release_status!r} requires a release tag")
    contract_relative, contract_file = _root_relative_existing_path(
        root, contract_path, "revision envelope contract path"
    )
    lock_relative, lock_file = _root_relative_existing_path(
        root, lock_path, "revision envelope lock path"
    )
    if release_status in {"tagged", "released"}:
        _verify_git_binding(
            root=root,
            source_commit=source_commit,
            release_status=release_status,
            release_tag=release_tag,
            contract_relative=contract_relative,
            contract_file=contract_file,
            lock_relative=lock_relative,
            lock_file=lock_file,
        )
    validate_contract_path(
        contract_file,
        schema_path=_path_argument(root, contract_schema_path),
        root=root,
    )
    envelope: dict[str, Any] = {
        "schema_version": REVISION_ENVELOPE_SCHEMA_VERSION,
        "producer_id": "robot_sf",
        "repository_url": REPOSITORY_URL,
        "source_commit": source_commit,
        "release_status": release_status,
        "contract": {"path": contract_relative, "sha256": sha256_file(contract_file)},
        "lock": {"path": lock_relative, "sha256": sha256_file(lock_file)},
        "generator": {
            "path": SCRIPT_PATH.as_posix(),
            "version": GENERATOR_VERSION,
            "canonicalization_profile": CANONICALIZATION_PROFILE,
        },
    }
    if release_tag is not None:
        envelope["release_tag"] = release_tag
    revision_schema = _load_schema(
        _path_argument(root, revision_schema_path), "ecosystem revision envelope schema"
    )
    _validate_against_schema(envelope, revision_schema, "ecosystem revision envelope")
    return envelope


def validate_revision_envelope_path(
    path: Path,
    *,
    root: Path,
    contract_schema_path: Path,
    revision_schema_path: Path,
) -> dict[str, Any]:
    """Validate canonical envelope bytes and every digest-bound referenced file."""
    envelope = _mapping(load_json(path), f"revision envelope {path}")
    revision_schema = _load_schema(
        _path_argument(root, revision_schema_path), "ecosystem revision envelope schema"
    )
    _validate_against_schema(envelope, revision_schema, "ecosystem revision envelope")
    if path.read_bytes() != canonical_bytes(envelope):
        raise ContractError(f"revision envelope {path} is not canonical RFC 8785 bytes")
    for field in ("contract", "lock"):
        record = _mapping(envelope[field], f"revision envelope {field}")
        _relative, resolved = _repo_relative_path(
            root, record["path"], f"revision envelope {field}.path"
        )
        actual = sha256_file(resolved)
        if record["sha256"] != actual:
            raise ContractError(
                f"stale revision envelope {field} digest: expected {actual}, got {record['sha256']}"
            )
        if field == "contract":
            validate_contract_path(
                resolved,
                schema_path=_path_argument(root, contract_schema_path),
                root=root,
            )
    if envelope["release_status"] in {"tagged", "released"}:
        contract_relative = str(envelope["contract"]["path"])
        lock_relative = str(envelope["lock"]["path"])
        _verify_git_binding(
            root=root,
            source_commit=str(envelope["source_commit"]),
            release_status=str(envelope["release_status"]),
            release_tag=str(envelope.get("release_tag")),
            contract_relative=contract_relative,
            contract_file=root / contract_relative,
            lock_relative=lock_relative,
            lock_file=root / lock_relative,
        )
    return envelope


def _json_report(value: Mapping[str, Any]) -> str:
    """Render a human-reviewable deterministic JSON report."""
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _parser() -> argparse.ArgumentParser:
    """Construct the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--check", action="store_true", help="Fail if committed outputs are stale.")
    action.add_argument("--validate", type=Path, metavar="CONTRACT", help="Validate a contract.")
    action.add_argument(
        "--compare",
        type=Path,
        nargs=2,
        metavar=("BASELINE", "CANDIDATE"),
        help="Validate a candidate change declaration against a baseline.",
    )
    action.add_argument(
        "--write-revision-envelope",
        type=Path,
        metavar="OUTPUT",
        help="Write a commit/tag/lock revision envelope.",
    )
    action.add_argument(
        "--validate-revision-envelope",
        type=Path,
        metavar="ENVELOPE",
        help="Validate a revision envelope and all bound digests.",
    )
    parser.add_argument("--root", type=Path, default=repository_root())
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY_PATH)
    parser.add_argument("--contract-schema", type=Path, default=DEFAULT_CONTRACT_SCHEMA_PATH)
    parser.add_argument("--revision-schema", type=Path, default=DEFAULT_REVISION_SCHEMA_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_CONTRACT_PATH)
    parser.add_argument("--digest-output", type=Path, default=DEFAULT_DIGEST_PATH)
    parser.add_argument("--digest-file", type=Path, help="Digest sidecar used with --validate.")
    parser.add_argument("--verify-sources", action="store_true", help="Re-resolve contract inputs.")
    parser.add_argument("--requirements", type=Path, help="Requirements used with --validate.")
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK_PATH)
    parser.add_argument("--source-commit", help="Full Git SHA for a revision envelope.")
    parser.add_argument(
        "--release-status",
        choices=("unreleased", "tagged", "released"),
        default="unreleased",
    )
    parser.add_argument("--release-tag")
    return parser


def _validate_cli_combinations(args: argparse.Namespace) -> None:
    """Fail closed on arguments that do not belong to the selected action."""
    if args.requirements is not None and args.validate is None:
        raise ContractError("--requirements requires --validate")
    if args.digest_file is not None and args.validate is None:
        raise ContractError("--digest-file requires --validate")
    if args.verify_sources and args.validate is None:
        raise ContractError("--verify-sources requires --validate")
    envelope_options_used = (
        args.source_commit is not None
        or args.release_tag is not None
        or args.release_status != "unreleased"
    )
    if envelope_options_used and args.write_revision_envelope is None:
        raise ContractError("revision metadata options require --write-revision-envelope")
    if args.write_revision_envelope is not None and args.source_commit is None:
        raise ContractError("--write-revision-envelope requires --source-commit")


def _run(args: argparse.Namespace) -> int:
    """Execute one validated CLI action and return a process exit code."""
    _validate_cli_combinations(args)
    root = args.root.resolve()
    contract_schema_path = _path_argument(root, args.contract_schema)
    if args.check:
        contract = check_contract(
            root=root,
            registry_path=args.registry,
            schema_path=args.contract_schema,
            output_path=args.output,
            digest_path=args.digest_output,
        )
        print(f"ecosystem contract is current: {contract['contract_digest']['value']}")
        return 0
    if args.validate is not None:
        contract = validate_contract_path(
            _path_argument(root, args.validate),
            schema_path=contract_schema_path,
            root=root,
            digest_path=(
                _path_argument(root, args.digest_file) if args.digest_file is not None else None
            ),
            verify_sources=args.verify_sources,
        )
        if args.requirements is not None:
            requirements = _mapping(
                load_json(_path_argument(root, args.requirements)), "ecosystem requirements"
            )
            schema = _load_schema(contract_schema_path, "ecosystem contract schema")
            report = check_compatibility(contract, requirements, schema=schema)
            print(_json_report(report), end="")
            if not report["compatible"]:
                raise CompatibilityError("contract does not meet the supplied requirements")
        else:
            print(f"ecosystem contract is valid: {contract['contract_digest']['value']}")
        return 0
    if args.compare is not None:
        schema = _load_schema(contract_schema_path, "ecosystem contract schema")
        baseline = validate_contract_path(
            _path_argument(root, args.compare[0]), schema_path=contract_schema_path, root=root
        )
        candidate = validate_contract_path(
            _path_argument(root, args.compare[1]), schema_path=contract_schema_path, root=root
        )
        report = check_declared_change(baseline, candidate, schema=schema)
        print(_json_report(report), end="")
        if not report["valid"]:
            raise CompatibilityError("candidate contract change declaration is invalid")
        return 0
    if args.write_revision_envelope is not None:
        envelope = build_revision_envelope(
            root=root,
            contract_path=args.output,
            contract_schema_path=args.contract_schema,
            revision_schema_path=args.revision_schema,
            lock_path=args.lock,
            source_commit=args.source_commit,
            release_status=args.release_status,
            release_tag=args.release_tag,
        )
        output = _path_argument(root, args.write_revision_envelope)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(canonical_bytes(envelope))
        validate_revision_envelope_path(
            output,
            root=root,
            contract_schema_path=args.contract_schema,
            revision_schema_path=args.revision_schema,
        )
        print(f"wrote ecosystem revision envelope: {output}")
        return 0
    if args.validate_revision_envelope is not None:
        validate_revision_envelope_path(
            _path_argument(root, args.validate_revision_envelope),
            root=root,
            contract_schema_path=args.contract_schema,
            revision_schema_path=args.revision_schema,
        )
        print("ecosystem revision envelope is valid")
        return 0
    contract = write_contract(
        root=root,
        registry_path=args.registry,
        schema_path=args.contract_schema,
        output_path=args.output,
        digest_path=args.digest_output,
    )
    print(f"wrote ecosystem contract: {contract['contract_digest']['value']}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Run the ecosystem contract CLI with typed fail-closed exit codes."""
    args = _parser().parse_args(argv)
    try:
        return _run(args)
    except ContractDriftError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except CompatibilityError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 3
    except (ContractError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
