/* Offline SREV-16 panel controller.
 *
 * The model is generated by review_panels.py.  This module owns only transient
 * browser state.  Every seek is one dispatch against one shared source-time
 * cursor; individual panels render the resulting snapshot and never seek one
 * another, which prevents feedback loops.
 */

export const PANEL_MODEL_SCHEMA_VERSION = "review-panels.v1";
export const DEFAULT_SPEEDS = [0.25, 0.5, 1.0, 2.0, 4.0];

export function nearestSample(stream, targetTimeS) {
  const samples = Array.isArray(stream?.samples) ? stream.samples : [];
  const resolution = Number.isFinite(stream?.resolution_s) ? stream.resolution_s : 0;
  if (stream?.status === "unavailable" || samples.length === 0) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: null,
      temporal_error_s: null,
      resolution_s: resolution,
      reason: "stream_unavailable",
    };
  }
  let selected = samples[0];
  let error = Math.abs(Number(selected.time_s) - targetTimeS);
  for (const sample of samples.slice(1)) {
    const candidateError = Math.abs(Number(sample.time_s) - targetTimeS);
    // Ties intentionally retain the earlier sample.
    if (candidateError < error || (candidateError === error && Number(sample.time_s) < Number(selected.time_s))) {
      selected = sample;
      error = candidateError;
    }
  }
  if (error > resolution + 1e-12) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: selected.time_s,
      temporal_error_s: error,
      resolution_s: resolution,
      source_index: selected.source_index,
      reason: "outside_declared_resolution",
    };
  }
  if (selected.missing) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: selected.time_s,
      temporal_error_s: error,
      resolution_s: resolution,
      source_index: selected.source_index,
      reason: "sample_missing",
    };
  }
  return {
    status: "available",
    target_time_s: targetTimeS,
    sample_time_s: selected.time_s,
    temporal_error_s: error,
    resolution_s: resolution,
    source_index: selected.source_index,
    value: selected.value,
    reason: "",
  };
}

function clamp(value, minimum, maximum) {
  return Math.min(Math.max(value, minimum), maximum);
}

function streamForPanel(model, panel) {
  if (panel === "scene" || panel === "video") return model?.streams?.[panel] || null;
  if (panel.startsWith("metric:")) return model?.streams?.[panel] || null;
  return null;
}

function streamSnapshot(model, panel, timeS) {
  const stream = streamForPanel(model, panel);
  const selected = nearestSample(stream, timeS);
  return {
    panel,
    ...selected,
    cursor_time_s: timeS,
  };
}

export class ReviewPanelsController {
  constructor(model, root = null) {
    this.model = model || {};
    this.root = root;
    const time = this.model.time || {};
    const cursor = time.cursor || this.model.context?.cursor || {};
    const start = Number.isFinite(Number(time.origin_s)) ? Number(time.origin_s) : 0;
    const end = Number.isFinite(Number(time.terminal_s)) ? Number(time.terminal_s) : start;
    this.state = {
      cursorTimeS: Number.isFinite(Number(cursor.time_s)) ? Number(cursor.time_s) : start,
      contextRevision: Number(this.model.context?.context_revision || cursor.context_revision || 0),
      intervalId: this.model.context?.interval_id || null,
      playing: false,
      speed: Number(this.model.controls?.default_speed || 1.0),
      metricVisibility: Object.fromEntries(
        Object.entries(this.model.metrics || {}).map(([id, metric]) => [id, metric.visible !== false])
      ),
      start,
      end,
    };
    this._lastDispatch = null;
    if (this.root) this.render();
  }

  snapshot() {
    const timeS = this.state.cursorTimeS;
    const metrics = {};
    for (const metricId of Object.keys(this.model.metrics || {})) {
      metrics[metricId] = {
        ...this.model.metrics[metricId],
        visible: this.state.metricVisibility[metricId] !== false,
        current: streamSnapshot(this.model, `metric:${metricId}`, timeS),
      };
    }
    const events = (this.model.events || []).map((event) => ({
      ...event,
      selected: Number(event.start_s) <= timeS && timeS <= Number(event.end_s),
    }));
    return {
      cursor: {
        time_s: timeS,
        context_revision: this.state.contextRevision,
        source: this._lastDispatch?.source || "initial",
        interval_id: this.state.intervalId,
      },
      context_revision: this.state.contextRevision,
      scene: streamSnapshot(this.model, "scene", timeS),
      video: streamSnapshot(this.model, "video", timeS),
      metrics,
      events,
    };
  }

  dispatch(action = {}) {
    const type = action.type || "";
    if (type === "seek") {
      const value = Number(action.time_s);
      if (!Number.isFinite(value)) return this.snapshot();
      const next = clamp(value, this.state.start, this.state.end);
      if (next !== this.state.cursorTimeS || action.force_revision) this.state.contextRevision += 1;
      this.state.cursorTimeS = next;
      this._lastDispatch = { type, source: action.source || "seek" };
    } else if (type === "step") {
      const samples = this.model.streams?.scene?.samples || [];
      if (samples.length) {
        const current = samples.findIndex((sample) => Number(sample.time_s) >= this.state.cursorTimeS);
        const index = Math.max(0, Math.min(samples.length - 1, (current < 0 ? samples.length - 1 : current) + Number(action.delta || 0)));
        this.state.cursorTimeS = Number(samples[index].time_s);
        this.state.contextRevision += 1;
        this._lastDispatch = { type, source: action.source || "keyboard" };
      }
    } else if (type === "toggle-play") {
      this.state.playing = !this.state.playing;
      this._lastDispatch = { type, source: action.source || "keyboard" };
    } else if (type === "set-speed") {
      const speed = Number(action.speed);
      if (Number.isFinite(speed) && speed > 0) this.state.speed = speed;
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "set-interval") {
      const intervalId = action.interval_id == null ? null : String(action.interval_id);
      const interval = (this.model.intervals || []).find((candidate) => candidate.interval_id === intervalId);
      this.state.intervalId = intervalId;
      if (interval) {
        this.state.start = Number(interval.start_s);
        this.state.end = Number(interval.end_s);
        this.state.cursorTimeS = clamp(this.state.cursorTimeS, this.state.start, this.state.end);
      } else {
        this.state.start = Number(this.model.time?.origin_s ?? 0);
        this.state.end = Number(this.model.time?.terminal_s ?? this.state.start);
        this.state.cursorTimeS = clamp(this.state.cursorTimeS, this.state.start, this.state.end);
      }
      this.state.contextRevision += 1;
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "toggle-metric") {
      const metricId = String(action.metric_id || "");
      if (Object.prototype.hasOwnProperty.call(this.state.metricVisibility, metricId)) {
        this.state.metricVisibility[metricId] = !this.state.metricVisibility[metricId];
      }
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "metric-seek") {
      const metricId = String(action.metric_id || "");
      const metric = this.model.metrics?.[metricId];
      const candidate = action.time_s ?? metric?.current?.sample_time_s;
      if (metric && Number.isFinite(Number(candidate))) {
        this.dispatch({ type: "seek", time_s: candidate, source: "metric" });
      }
    } else if (type === "event-seek") {
      const event = (this.model.events || []).find((candidate) => String(candidate.event_id) === String(action.event_id));
      if (event) this.dispatch({ type: "seek", time_s: event.seek_time_s ?? event.start_s, source: "event" });
    }
    if (this.root) this.render();
    return this.snapshot();
  }

  handleKey(event) {
    const tagName = String(event.target?.tagName || "").toLowerCase();
    if (tagName === "input" || tagName === "textarea" || tagName === "select" || event.target?.isContentEditable) return false;
    if (event.code === "Space") {
      event.preventDefault();
      this.dispatch({ type: "toggle-play", source: "keyboard" });
      return true;
    }
    if (event.code === "ArrowLeft") {
      event.preventDefault();
      this.dispatch({ type: "step", delta: -1, source: "keyboard" });
      return true;
    }
    if (event.code === "ArrowRight") {
      event.preventDefault();
      this.dispatch({ type: "step", delta: 1, source: "keyboard" });
      return true;
    }
    if (event.key === "+" || event.key === "=") {
      this.adjustSpeed(1);
      return true;
    }
    if (event.key === "-" || event.key === "_") {
      this.adjustSpeed(-1);
      return true;
    }
    return false;
  }

  adjustSpeed(direction) {
    const speeds = this.model.controls?.speeds || DEFAULT_SPEEDS;
    const current = speeds.findIndex((speed) => Number(speed) >= this.state.speed);
    const index = current < 0 ? speeds.length - 1 : Math.max(0, Math.min(speeds.length - 1, current + direction));
    this.dispatch({ type: "set-speed", speed: Number(speeds[index]), source: "keyboard" });
  }

  render() {
    if (!this.root) return;
    this.root.replaceChildren();
    const toolbar = document.createElement("div");
    toolbar.className = "toolbar";
    const play = document.createElement("button");
    play.type = "button";
    play.textContent = this.state.playing ? "Pause" : "Play";
    play.addEventListener("click", () => this.dispatch({ type: "toggle-play", source: "control" }));
    toolbar.appendChild(play);
    for (const [label, delta] of [["Previous", -1], ["Next", 1]]) {
      const button = document.createElement("button");
      button.type = "button";
      button.textContent = label;
      button.addEventListener("click", () => this.dispatch({ type: "step", delta, source: "control" }));
      toolbar.appendChild(button);
    }
    const speed = document.createElement("select");
    for (const value of this.model.controls?.speeds || DEFAULT_SPEEDS) {
      const option = document.createElement("option");
      option.value = String(value);
      option.textContent = `${value}×`;
      option.selected = Number(value) === this.state.speed;
      speed.appendChild(option);
    }
    speed.addEventListener("change", () => this.dispatch({ type: "set-speed", speed: speed.value, source: "control" }));
    toolbar.appendChild(speed);
    const interval = document.createElement("select");
    const whole = document.createElement("option");
    whole.value = "";
    whole.textContent = "Whole episode";
    interval.appendChild(whole);
    for (const item of this.model.intervals || []) {
      const option = document.createElement("option");
      option.value = item.interval_id;
      option.textContent = item.label || item.interval_id;
      option.selected = item.interval_id === this.state.intervalId;
      interval.appendChild(option);
    }
    interval.addEventListener("change", () => this.dispatch({ type: "set-interval", interval_id: interval.value || null, source: "control" }));
    toolbar.appendChild(interval);
    this.root.appendChild(toolbar);

    const slider = document.createElement("input");
    slider.type = "range";
    slider.min = String(this.state.start);
    slider.max = String(this.state.end);
    slider.step = "any";
    slider.value = String(this.state.cursorTimeS);
    slider.addEventListener("input", () => this.dispatch({ type: "seek", time_s: slider.value, source: "scrubber" }));
    this.root.appendChild(slider);
    const cursor = document.createElement("p");
    cursor.className = "muted";
    cursor.textContent = `simulation time ${this.state.cursorTimeS.toFixed(3)} s | context revision ${this.state.contextRevision} | nearest samples; no interpolation`;
    this.root.appendChild(cursor);

    const grid = document.createElement("div");
    grid.className = "grid";
    grid.appendChild(this._panel("Scene", this.snapshot().scene));
    grid.appendChild(this._panel("Video", this.snapshot().video));
    grid.appendChild(this._metricsPanel());
    grid.appendChild(this._eventsPanel());
    this.root.appendChild(grid);
    document.body.onkeydown = (event) => this.handleKey(event);
  }

  _panel(title, snapshot) {
    const section = document.createElement("section");
    section.className = "panel";
    const heading = document.createElement("h2");
    heading.textContent = title;
    section.appendChild(heading);
    const text = document.createElement("p");
    text.className = snapshot.status === "available" ? "muted" : "unavailable";
    if (snapshot.status === "available") {
      text.textContent = `sample ${Number(snapshot.sample_time_s).toFixed(3)} s | error ${Number(snapshot.temporal_error_s).toFixed(3)} s | resolution ${Number(snapshot.resolution_s).toFixed(3)} s`;
      const pre = document.createElement("pre");
      pre.textContent = JSON.stringify(snapshot.value, null, 2);
      section.appendChild(text);
      section.appendChild(pre);
    } else {
      text.textContent = `unavailable: ${snapshot.reason || "not recorded"} | resolution ${Number(snapshot.resolution_s || 0).toFixed(3)} s`;
      section.appendChild(text);
    }
    return section;
  }

  _metricsPanel() {
    const section = document.createElement("section");
    section.className = "panel";
    const heading = document.createElement("h2");
    heading.textContent = "Metrics";
    section.appendChild(heading);
    for (const [metricId, metric] of Object.entries(this.snapshot().metrics)) {
      const row = document.createElement("div");
      row.className = "metric-row";
      const toggle = document.createElement("input");
      toggle.type = "checkbox";
      toggle.checked = metric.visible;
      toggle.addEventListener("change", () => this.dispatch({ type: "toggle-metric", metric_id: metricId, source: "control" }));
      row.appendChild(toggle);
      const label = document.createElement("span");
      const unit = metric.unit || "unit unavailable";
      const current = metric.current;
      label.textContent = `${metric.label} [${unit}] — ${current.status === "available" ? String(current.value) : `missing (${current.reason})`}`;
      row.appendChild(label);
      row.addEventListener("click", (event) => {
        if (event.target === toggle) return;
        this.dispatch({ type: "metric-seek", metric_id: metricId, source: "metric" });
      });
      section.appendChild(row);
    }
    if (!Object.keys(this.model.metrics || {}).length) {
      const empty = document.createElement("p");
      empty.className = "unavailable";
      empty.textContent = "unavailable: no metric series recorded";
      section.appendChild(empty);
    }
    return section;
  }

  _eventsPanel() {
    const section = document.createElement("section");
    section.className = "panel";
    const heading = document.createElement("h2");
    heading.textContent = "Events";
    section.appendChild(heading);
    for (const event of this.snapshot().events) {
      const button = document.createElement("button");
      button.type = "button";
      button.textContent = `${event.event_type} ${event.start_s}–${event.end_s}${event.selected ? " (selected)" : ""}`;
      button.addEventListener("click", () => this.dispatch({ type: "event-seek", event_id: event.event_id, source: "event" }));
      section.appendChild(button);
    }
    if (!this.model.events?.length) {
      const empty = document.createElement("p");
      empty.className = "unavailable";
      empty.textContent = "unavailable: no event intervals recorded";
      section.appendChild(empty);
    }
    return section;
  }
}

export function createPanelController(model, root = null) {
  return new ReviewPanelsController(model, root);
}

export function mountReviewPanels(model, root) {
  return createPanelController(model, root);
}

const dataElement = typeof document === "undefined" ? null : document.getElementById("review-panels-data");
const root = typeof document === "undefined" ? null : document.getElementById("review-panels-root");
if (dataElement && root) {
  try {
    const model = JSON.parse(dataElement.textContent || "{}");
    createPanelController(model, root);
  } catch (error) {
    root.textContent = `Unable to load review panel model: ${error}`;
  }
}
