/* Offline SREV-16 synchronized scene/video/metric/event panels.
 *
 * The model is generated by review_panels.py.  This module owns transient
 * browser state only: one source-time cursor, one playback clock, and one
 * render pass for every panel.  It has no network imports and never starts a
 * simulator, planner, AI provider, or annotation writer.
 */

export const PANEL_MODEL_SCHEMA_VERSION = "review-panels.v1";
export const DEFAULT_SPEEDS = [0.25, 0.5, 1.0, 2.0, 4.0];

const NOOP_SCHEDULER = Object.freeze({
  request: () => null,
  cancel: () => {},
});

function defaultNow() {
  if (typeof performance !== "undefined" && typeof performance.now === "function") {
    return performance.now();
  }
  return Date.now();
}

function browserScheduler() {
  if (typeof requestAnimationFrame === "function") {
    return {
      request: (callback) => requestAnimationFrame(callback),
      cancel: (handle) => {
        if (typeof cancelAnimationFrame === "function") cancelAnimationFrame(handle);
      },
    };
  }
  if (typeof setTimeout === "function") {
    return {
      request: (callback) => setTimeout(() => callback(defaultNow()), 16),
      cancel: (handle) => clearTimeout(handle),
    };
  }
  return NOOP_SCHEDULER;
}

function resolveScheduler(options, root) {
  const supplied = options?.scheduler;
  if (supplied && typeof supplied.request === "function") {
    return {
      request: supplied.request.bind(supplied),
      cancel: typeof supplied.cancel === "function" ? supplied.cancel.bind(supplied) : () => {},
    };
  }
  if (root || typeof window !== "undefined") return browserScheduler();
  return NOOP_SCHEDULER;
}

function finiteNumber(value, fallback = null) {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
}

function clamp(value, minimum, maximum) {
  return Math.min(Math.max(value, minimum), maximum);
}

function trustedOfflineMediaUri(uri, allowedSchemes = []) {
  if (typeof uri !== "string") return false;
  const value = uri.trim();
  if (!value || value.startsWith("/") || value.startsWith("\\") || value.startsWith("//")) {
    return false;
  }
  let decoded = value;
  try {
    decoded = decodeURIComponent(value);
  } catch (_error) {
    return false;
  }
  if (decoded.includes("?") || decoded.includes("#") || decoded.includes("\\")) return false;
  const path = decoded.split(/[?#]/, 1)[0];
  if (path.split(/[\\/]/).some((part) => part === "..")) return false;
  const scheme = /^([a-z][a-z\d+.-]*):/i.exec(decoded)?.[1]?.toLowerCase();
  if (!scheme) return true;
  return allowedSchemes.some((candidate) => String(candidate).toLowerCase() === scheme);
}

function scalarMetricValue(value) {
  let current = value;
  for (let depth = 0; depth < 3; depth += 1) {
    if (!current || typeof current !== "object" || !Object.prototype.hasOwnProperty.call(current, "value")) {
      break;
    }
    const nested = current.value;
    if (nested && typeof nested === "object") {
      current = nested;
      continue;
    }
    return nested;
  }
  return current;
}

function displayMetricValue(value) {
  const scalar = scalarMetricValue(value);
  if (scalar === null || scalar === undefined) return "missing";
  if (typeof scalar === "object") {
    try {
      return JSON.stringify(scalar);
    } catch (_error) {
      return "unavailable";
    }
  }
  return String(scalar);
}

export function nearestSample(stream, targetTimeS) {
  const samples = Array.isArray(stream?.samples) ? stream.samples : [];
  const resolution = Number.isFinite(stream?.resolution_s) ? stream.resolution_s : 0;
  const unavailableReason = stream?.reason || "stream_unavailable";
  if (stream?.status === "unavailable" || samples.length === 0) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: null,
      temporal_error_s: null,
      resolution_s: resolution,
      reason: unavailableReason,
    };
  }
  let selected = samples[0];
  let error = Math.abs(Number(selected.time_s) - targetTimeS);
  for (const sample of samples.slice(1)) {
    const candidateError = Math.abs(Number(sample.time_s) - targetTimeS);
    // Ties intentionally retain the earlier sample.
    if (
      candidateError < error ||
      (candidateError === error && Number(sample.time_s) < Number(selected.time_s))
    ) {
      selected = sample;
      error = candidateError;
    }
  }
  if (error > resolution + 1e-12) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: selected.time_s,
      temporal_error_s: error,
      resolution_s: resolution,
      source_index: selected.source_index,
      reason: "outside_declared_resolution",
    };
  }
  if (selected.missing) {
    return {
      status: "unavailable",
      target_time_s: targetTimeS,
      sample_time_s: selected.time_s,
      temporal_error_s: error,
      resolution_s: resolution,
      source_index: selected.source_index,
      reason: "sample_missing",
    };
  }
  return {
    status: "available",
    target_time_s: targetTimeS,
    sample_time_s: selected.time_s,
    temporal_error_s: error,
    resolution_s: resolution,
    source_index: selected.source_index,
    value: selected.value,
    reason: "",
  };
}

function streamForPanel(model, panel) {
  if (panel === "scene" || panel === "video") return model?.streams?.[panel] || null;
  if (panel.startsWith("metric:")) return model?.streams?.[panel] || null;
  return null;
}

function streamSnapshot(model, panel, timeS) {
  const stream = streamForPanel(model, panel);
  const selected = nearestSample(stream, timeS);
  return {
    panel,
    ...selected,
    cursor_time_s: timeS,
    surface: stream?.surface || {},
    media_uri: stream?.media_uri || null,
  };
}

function sourceVideoUri(model, snapshot) {
  if (typeof snapshot?.media_uri === "string" && snapshot.media_uri) return snapshot.media_uri;
  const identity = model?.source_identity || {};
  const stream = model?.streams?.video || {};
  const sourceId = stream.source_ids?.[0];
  const candidate = sourceId ? identity[sourceId]?.media_uri : null;
  return typeof candidate === "string" && candidate ? candidate : null;
}

function pointValue(candidate) {
  if (Array.isArray(candidate) && candidate.length >= 2) {
    const x = finiteNumber(candidate[0]);
    const y = finiteNumber(candidate[1]);
    if (x !== null && y !== null) return [x, y];
  }
  if (candidate && typeof candidate === "object") {
    const x = finiteNumber(candidate.x);
    const y = finiteNumber(candidate.y);
    if (x !== null && y !== null) return [x, y];
  }
  return null;
}

function scenePositions(snapshot) {
  const value = snapshot?.value && typeof snapshot.value === "object" ? snapshot.value : {};
  const robot = value.robot && typeof value.robot === "object" ? value.robot : null;
  const pedestrians = Array.isArray(value.pedestrians) ? value.pedestrians : [];
  const points = [];
  const robotPoint = pointValue(robot?.position);
  if (robotPoint) points.push({ point: robotPoint, kind: "robot" });
  for (const pedestrian of pedestrians) {
    const point = pointValue(pedestrian?.position);
    if (point) points.push({ point, kind: "pedestrian" });
  }
  return points;
}

function mapBounds(surface, positions, goal) {
  const map = surface?.map;
  const origin = pointValue(map?.origin) || [0, 0];
  const width = finiteNumber(map?.width);
  const height = finiteNumber(map?.height);
  if (width !== null && height !== null && width > 0 && height > 0) {
    return [origin[0], origin[1], origin[0] + width, origin[1] + height];
  }
  const points = [...positions.map((entry) => entry.point), ...(goal ? [goal] : [])];
  const bounds = Array.isArray(map?.bounds) ? map.bounds : [];
  for (const line of bounds) {
    if (Array.isArray(line) && line.length >= 4) {
      points.push([Number(line[0]), Number(line[1])], [Number(line[2]), Number(line[3])]);
    }
  }
  if (!points.length) return [-1, -1, 1, 1];
  const xs = points.map((point) => point[0]).filter(Number.isFinite);
  const ys = points.map((point) => point[1]).filter(Number.isFinite);
  if (!xs.length || !ys.length) return [-1, -1, 1, 1];
  const pad = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys), 1) * 0.1;
  return [Math.min(...xs) - pad, Math.min(...ys) - pad, Math.max(...xs) + pad, Math.max(...ys) + pad];
}

function drawSceneCanvas(canvas, model, snapshot) {
  const context = canvas.getContext?.("2d");
  if (!context) return;
  const width = canvas.width;
  const height = canvas.height;
  context.clearRect(0, 0, width, height);
  context.fillStyle = "#0f172a";
  context.fillRect(0, 0, width, height);
  if (snapshot?.status !== "available") {
    context.fillStyle = "#fca5a5";
    context.font = "14px system-ui, sans-serif";
    context.fillText(`scene unavailable: ${snapshot?.reason || "not recorded"}`, 12, 24);
    return;
  }
  const surface = model?.scene_surface || snapshot.surface || {};
  const goal = pointValue(model?.goal_geometry?.point?.value || model?.goal_geometry?.goal_point);
  const positions = scenePositions(snapshot);
  const [minX, minY, maxX, maxY] = mapBounds(surface, positions, goal);
  const spanX = Math.max(maxX - minX, 1e-9);
  const spanY = Math.max(maxY - minY, 1e-9);
  const margin = 16;
  const scale = Math.min((width - 2 * margin) / spanX, (height - 2 * margin) / spanY);
  const toCanvas = ([x, y]) => [margin + (x - minX) * scale, height - margin - (y - minY) * scale];
  const map = surface.map || {};
  const bounds = Array.isArray(map?.bounds) ? map.bounds : [];
  const obstacles = Array.isArray(map?.obstacles) ? map.obstacles : [];
  context.strokeStyle = "#64748b";
  context.lineWidth = 1;
  for (const line of bounds) {
    if (!Array.isArray(line) || line.length < 4) continue;
    const start = pointValue([line[0], line[1]]);
    const end = pointValue([line[2], line[3]]);
    if (!start || !end) continue;
    const startCanvas = toCanvas(start);
    const endCanvas = toCanvas(end);
    context.beginPath();
    context.moveTo(startCanvas[0], startCanvas[1]);
    context.lineTo(endCanvas[0], endCanvas[1]);
    context.stroke();
  }
  context.strokeStyle = "#ef4444";
  for (const obstacle of obstacles) {
    const lines = Array.isArray(obstacle?.lines) ? obstacle.lines : [];
    if (lines.length) {
      for (const line of lines) {
        if (!Array.isArray(line) || line.length < 4) continue;
        const start = pointValue([line[0], line[1]]);
        const end = pointValue([line[2], line[3]]);
        if (!start || !end) continue;
        const startCanvas = toCanvas(start);
        const endCanvas = toCanvas(end);
        context.beginPath();
        context.moveTo(startCanvas[0], startCanvas[1]);
        context.lineTo(endCanvas[0], endCanvas[1]);
        context.stroke();
      }
      continue;
    }
    const vertices = Array.isArray(obstacle?.vertices) ? obstacle.vertices : [];
    const validVertices = vertices.map(pointValue).filter(Boolean);
    if (validVertices.length < 2) continue;
    context.beginPath();
    validVertices.forEach((vertex, index) => {
      const point = toCanvas(vertex);
      if (index === 0) context.moveTo(point[0], point[1]);
      else context.lineTo(point[0], point[1]);
    });
    context.closePath();
    context.stroke();
  }
  const goalZones = Array.isArray(map?.robot_goal_zones) ? map.robot_goal_zones : [];
  context.strokeStyle = "#22c55e";
  for (const zone of goalZones) {
    const vertices = Array.isArray(zone) ? zone.map(pointValue).filter(Boolean) : [];
    if (vertices.length < 3) continue;
    context.beginPath();
    vertices.forEach((vertex, index) => {
      const point = toCanvas(vertex);
      if (index === 0) context.moveTo(point[0], point[1]);
      else context.lineTo(point[0], point[1]);
    });
    context.closePath();
    context.stroke();
  }
  const trajectory = Array.isArray(surface.trajectory) ? surface.trajectory : [];
  if (trajectory.length > 1) {
    context.strokeStyle = "#38bdf8";
    context.beginPath();
    trajectory.forEach((candidate, index) => {
      const point = pointValue(candidate);
      if (!point) return;
      const canvasPoint = toCanvas(point);
      if (index === 0) context.moveTo(canvasPoint[0], canvasPoint[1]);
      else context.lineTo(canvasPoint[0], canvasPoint[1]);
    });
    context.stroke();
  }
  if (goal) {
    const goalCanvas = toCanvas(goal);
    context.strokeStyle = "#22c55e";
    context.beginPath();
    context.arc(goalCanvas[0], goalCanvas[1], 6, 0, Math.PI * 2);
    context.stroke();
    const boundary = model?.goal_geometry?.completion_boundary?.value;
    const radius = finiteNumber(boundary?.radius_m ?? boundary?.radius);
    if (radius !== null && radius > 0) {
      context.beginPath();
      context.arc(goalCanvas[0], goalCanvas[1], radius * scale, 0, Math.PI * 2);
      context.stroke();
    }
  }
  for (const entry of positions) {
    const point = toCanvas(entry.point);
    context.fillStyle = entry.kind === "robot" ? "#22c55e" : "#f59e0b";
    context.beginPath();
    context.arc(point[0], point[1], entry.kind === "robot" ? 5 : 4, 0, Math.PI * 2);
    context.fill();
  }
  context.fillStyle = "#cbd5e1";
  context.font = "12px system-ui, sans-serif";
  context.fillText(`source time ${Number(snapshot.sample_time_s).toFixed(3)} s`, 12, height - 8);
}

export function mountSceneViewer(container, model, snapshot) {
  const documentRef = container?.ownerDocument || (typeof document === "undefined" ? null : document);
  if (!container || !documentRef) return { render: () => {}, unmount: () => {}, canvas: null };
  const canvas = documentRef.createElement("canvas");
  canvas.className = "review-scene-canvas";
  canvas.width = 640;
  canvas.height = 360;
  canvas.setAttribute?.("aria-label", "Recorded scene at the shared source-time cursor");
  container.appendChild(canvas);
  const render = (nextSnapshot = snapshot) => drawSceneCanvas(canvas, model, nextSnapshot);
  render(snapshot);
  return {
    canvas,
    render,
    unmount: () => canvas.remove?.(),
  };
}

function videoPresentationTime(value) {
  if (!value || typeof value !== "object") return null;
  return finiteNumber(
    value.pts_s ?? value.media_t_s ?? value.media_time_s ?? value.presentation_t_s,
  );
}

export class ReviewPanelsController {
  constructor(model, root = null, options = {}) {
    this.model = model || {};
    this.root = null;
    this._document = null;
    this._sceneMount = null;
    this._videoElement = null;
    this._frameHandle = null;
    this._playbackLastMs = null;
    this._allowedMediaSchemes = Array.isArray(options.allowedMediaSchemes)
      ? options.allowedMediaSchemes
      : [];
    this._videoTargetTime = null;
    const clock = options.clock || {};
    this._now = typeof options.now === "function"
      ? options.now
      : (typeof clock.now === "function" ? clock.now.bind(clock) : defaultNow);
    this._scheduler = resolveScheduler(options, root);
    const time = this.model.time || {};
    const cursor = this.model.context?.cursor || time.cursor || {};
    const globalStart = Number.isFinite(Number(time.origin_s)) ? Number(time.origin_s) : 0;
    const globalEnd = Number.isFinite(Number(time.terminal_s))
      ? Number(time.terminal_s)
      : globalStart;
    const selectedIntervalId = this.model.context?.interval_id || time.interval?.interval_id || null;
    const selectedInterval = (this.model.intervals || []).find(
      (interval) => String(interval.interval_id) === String(selectedIntervalId),
    );
    const intervalStart = Number(selectedInterval?.start_s ?? time.interval?.start_s);
    const intervalEnd = Number(selectedInterval?.end_s ?? time.interval?.end_s);
    const start = Number.isFinite(intervalStart) ? intervalStart : globalStart;
    const end = Number.isFinite(intervalEnd) ? intervalEnd : globalEnd;
    const initialCursor = Number.isFinite(Number(cursor.time_s)) ? Number(cursor.time_s) : start;
    this.state = {
      cursorTimeS: clamp(initialCursor, start, end),
      contextRevision: Number(this.model.context?.context_revision || cursor.context_revision || 0),
      intervalId: selectedIntervalId,
      playing: false,
      speed: Number(this.model.controls?.default_speed || 1.0),
      metricVisibility: Object.fromEntries(
        Object.entries(this.model.metrics || {}).map(([id, metric]) => [id, metric.visible !== false])
      ),
      start,
      end,
    };
    this._lastDispatch = null;
    this._controlCleanups = [];
    this._boundKeyHandler = (event) => this.handleKey(event);
    if (root) this.mount(root);
  }

  mount(root) {
    if (this.root === root) return this;
    if (this.root && this.root !== root) this.unmount();
    this.root = root;
    this._document = root?.ownerDocument || (typeof document === "undefined" ? null : document);
    if (this._document?.addEventListener) {
      this._document.addEventListener("keydown", this._boundKeyHandler);
    }
    this.render();
    return this;
  }

  unmount() {
    const staleRoot = this.root;
    this._pausePlayback();
    this._clearControlBindings();
    if (this._document?.removeEventListener) {
      this._document.removeEventListener("keydown", this._boundKeyHandler);
    }
    this._document = null;
    this._sceneMount?.unmount?.();
    this._sceneMount = null;
    this._videoElement?.pause?.();
    this._videoElement = null;
    this._videoTargetTime = null;
    if (staleRoot?.replaceChildren) {
      staleRoot.replaceChildren();
    } else {
      while (staleRoot?.firstChild) staleRoot.removeChild?.(staleRoot.firstChild);
    }
    this.root = null;
    return this;
  }

  _bindControl(target, type, handler) {
    target?.addEventListener?.(type, handler);
    this._controlCleanups.push(() => target?.removeEventListener?.(type, handler));
  }

  _clearControlBindings() {
    for (const cleanup of this._controlCleanups.splice(0)) cleanup();
  }

  snapshot() {
    const timeS = this.state.cursorTimeS;
    const metrics = {};
    for (const metricId of Object.keys(this.model.metrics || {})) {
      metrics[metricId] = {
        ...this.model.metrics[metricId],
        visible: this.state.metricVisibility[metricId] !== false,
        current: streamSnapshot(this.model, `metric:${metricId}`, timeS),
      };
    }
    const events = (this.model.events || []).map((event) => ({
      ...event,
      selected: Number(event.start_s) <= timeS && timeS <= Number(event.end_s),
    }));
    return {
      cursor: {
        time_s: timeS,
        context_revision: this.state.contextRevision,
        source: this._lastDispatch?.source || "initial",
        interval_id: this.state.intervalId,
      },
      context_revision: this.state.contextRevision,
      scene: streamSnapshot(this.model, "scene", timeS),
      video: streamSnapshot(this.model, "video", timeS),
      metrics,
      events,
    };
  }

  _applyCursor(value, source, forceRevision = false) {
    const next = clamp(value, this.state.start, this.state.end);
    if (next !== this.state.cursorTimeS || forceRevision) this.state.contextRevision += 1;
    this.state.cursorTimeS = next;
    this._lastDispatch = { type: "seek", source };
    return next;
  }

  _schedulePlayback() {
    if (!this.state.playing || this._frameHandle !== null) return;
    this._frameHandle = this._scheduler.request((timestamp) => {
      this._frameHandle = null;
      this.tick(timestamp);
      if (this.state.playing) this._schedulePlayback();
    });
  }

  _pausePlayback() {
    this.state.playing = false;
    this._playbackLastMs = null;
    if (this._frameHandle !== null) {
      this._scheduler.cancel(this._frameHandle);
      this._frameHandle = null;
    }
  }

  _resetPlaybackAnchor() {
    this._playbackLastMs = this.state.playing
      ? finiteNumber(this._now(), this._playbackLastMs ?? 0)
      : null;
  }

  _startPlayback() {
    if (this.state.playing) return;
    if (this.state.cursorTimeS >= this.state.end) {
      this._applyCursor(this.state.start, "restart", true);
    }
    this.state.playing = true;
    this._playbackLastMs = finiteNumber(this._now(), 0);
    this._schedulePlayback();
  }

  tick(nowMs = this._now()) {
    const now = finiteNumber(nowMs, this._playbackLastMs ?? 0);
    if (!this.state.playing) return this.snapshot();
    if (this._playbackLastMs === null) this._playbackLastMs = now;
    const elapsedMs = Math.max(0, now - this._playbackLastMs);
    this._playbackLastMs = now;
    const next = this.state.cursorTimeS + (elapsedMs / 1000) * this.state.speed;
    if (next >= this.state.end) {
      this._applyCursor(this.state.end, "playback");
      this._pausePlayback();
    } else if (next > this.state.cursorTimeS) {
      this._applyCursor(next, "playback");
    }
    if (this.root) this.render();
    return this.snapshot();
  }

  dispatch(action = {}) {
    const type = action.type || "";
    if (type === "seek") {
      const value = finiteNumber(action.time_s);
      if (value === null) return this.snapshot();
      this._applyCursor(value, action.source || "seek", Boolean(action.force_revision));
      this._resetPlaybackAnchor();
      if (this.state.cursorTimeS >= this.state.end) this._pausePlayback();
    } else if (type === "step") {
      const samples = this.model.streams?.scene?.samples || [];
      if (samples.length) {
        const current = samples.findIndex((sample) => Number(sample.time_s) >= this.state.cursorTimeS);
        const index = Math.max(
          0,
          Math.min(
            samples.length - 1,
            (current < 0 ? samples.length - 1 : current) + Number(action.delta || 0)
          )
        );
        this._applyCursor(Number(samples[index].time_s), action.source || "keyboard", true);
        this._resetPlaybackAnchor();
      }
    } else if (type === "toggle-play") {
      if (this.state.playing) this._pausePlayback();
      else this._startPlayback();
      this._lastDispatch = { type, source: action.source || "keyboard" };
    } else if (type === "set-speed") {
      const speed = finiteNumber(action.speed);
      if (speed !== null && speed > 0) {
        this.state.speed = speed;
        this._resetPlaybackAnchor();
      }
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "set-interval") {
      const intervalId = action.interval_id == null ? null : String(action.interval_id);
      const interval = (this.model.intervals || []).find((candidate) => candidate.interval_id === intervalId);
      this.state.intervalId = intervalId;
      if (interval) {
        this.state.start = Number(interval.start_s);
        this.state.end = Number(interval.end_s);
      } else {
        this.state.start = Number(this.model.time?.origin_s ?? 0);
        this.state.end = Number(this.model.time?.terminal_s ?? this.state.start);
      }
      this._applyCursor(clamp(this.state.cursorTimeS, this.state.start, this.state.end), "interval", true);
      this._resetPlaybackAnchor();
      if (this.state.cursorTimeS >= this.state.end) this._pausePlayback();
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "toggle-metric") {
      const metricId = String(action.metric_id || "");
      if (Object.prototype.hasOwnProperty.call(this.state.metricVisibility, metricId)) {
        this.state.metricVisibility[metricId] = !this.state.metricVisibility[metricId];
      }
      this._lastDispatch = { type, source: action.source || "control" };
    } else if (type === "metric-seek") {
      const metricId = String(action.metric_id || "");
      const metric = this.model.metrics?.[metricId];
      const candidate = action.time_s ?? metric?.current?.sample_time_s;
      const target = finiteNumber(candidate);
      if (metric && target !== null) {
        this._applyCursor(target, action.source || "metric", true);
        this._resetPlaybackAnchor();
      }
    } else if (type === "event-seek") {
      const event = (this.model.events || []).find(
        (candidate) => String(candidate.event_id) === String(action.event_id)
      );
      const target = finiteNumber(event?.seek_time_s ?? event?.start_s);
      if (event && target !== null) {
        this._applyCursor(target, action.source || "event", true);
        this._resetPlaybackAnchor();
      }
    }
    if (this.root) this.render();
    return this.snapshot();
  }

  handleKey(event) {
    const tagName = String(event.target?.tagName || "").toLowerCase();
    if (
      tagName === "input" ||
      tagName === "textarea" ||
      tagName === "select" ||
      event.target?.isContentEditable
    ) {
      return false;
    }
    if (event.code === "Space") {
      event.preventDefault();
      this.dispatch({ type: "toggle-play", source: "keyboard" });
      return true;
    }
    if (event.code === "ArrowLeft") {
      event.preventDefault();
      this.dispatch({ type: "step", delta: -1, source: "keyboard" });
      return true;
    }
    if (event.code === "ArrowRight") {
      event.preventDefault();
      this.dispatch({ type: "step", delta: 1, source: "keyboard" });
      return true;
    }
    if (event.key === "+" || event.key === "=") {
      event.preventDefault();
      this.adjustSpeed(1);
      return true;
    }
    if (event.key === "-" || event.key === "_") {
      event.preventDefault();
      this.adjustSpeed(-1);
      return true;
    }
    return false;
  }

  adjustSpeed(direction) {
    const speeds = this.model.controls?.speeds || DEFAULT_SPEEDS;
    const current = speeds.findIndex((speed) => Number(speed) >= this.state.speed);
    const index = current < 0 ? speeds.length - 1 : Math.max(0, Math.min(speeds.length - 1, current + direction));
    this.dispatch({ type: "set-speed", speed: Number(speeds[index]), source: "keyboard" });
  }

  render() {
    if (!this.root) return;
    this._clearControlBindings();
    this._sceneMount?.unmount?.();
    this._sceneMount = null;
    this.root.replaceChildren();
    const documentRef = this._document || this.root.ownerDocument || document;
    const toolbar = documentRef.createElement("div");
    toolbar.className = "toolbar";
    const play = documentRef.createElement("button");
    play.type = "button";
    play.textContent = this.state.playing ? "Pause" : "Play";
    this._bindControl(play, "click", () => this.dispatch({ type: "toggle-play", source: "control" }));
    toolbar.appendChild(play);
    for (const [label, delta] of [["Previous", -1], ["Next", 1]]) {
      const button = documentRef.createElement("button");
      button.type = "button";
      button.textContent = label;
      this._bindControl(button, "click", () => this.dispatch({ type: "step", delta, source: "control" }));
      toolbar.appendChild(button);
    }
    const speed = documentRef.createElement("select");
    for (const value of this.model.controls?.speeds || DEFAULT_SPEEDS) {
      const option = documentRef.createElement("option");
      option.value = String(value);
      option.textContent = `${value}×`;
      option.selected = Number(value) === this.state.speed;
      speed.appendChild(option);
    }
    this._bindControl(speed, "change", () => this.dispatch({ type: "set-speed", speed: speed.value, source: "control" }));
    toolbar.appendChild(speed);
    const interval = documentRef.createElement("select");
    const whole = documentRef.createElement("option");
    whole.value = "";
    whole.textContent = "Whole episode";
    interval.appendChild(whole);
    for (const item of this.model.intervals || []) {
      const option = documentRef.createElement("option");
      option.value = item.interval_id;
      option.textContent = item.label || item.interval_id;
      option.selected = item.interval_id === this.state.intervalId;
      interval.appendChild(option);
    }
    this._bindControl(interval, "change", () => this.dispatch({ type: "set-interval", interval_id: interval.value || null, source: "control" }));
    toolbar.appendChild(interval);
    this.root.appendChild(toolbar);

    const slider = documentRef.createElement("input");
    slider.type = "range";
    slider.min = String(this.state.start);
    slider.max = String(this.state.end);
    slider.step = "any";
    slider.value = String(this.state.cursorTimeS);
    this._bindControl(slider, "input", () => this.dispatch({ type: "seek", time_s: slider.value, source: "scrubber" }));
    this.root.appendChild(slider);
    const cursor = documentRef.createElement("p");
    cursor.className = "muted";
    cursor.textContent = `simulation time ${this.state.cursorTimeS.toFixed(3)} s | context revision ${this.state.contextRevision} | nearest samples; no interpolation`;
    this.root.appendChild(cursor);
    this.root.appendChild(this._contextPanel(documentRef));

    const grid = documentRef.createElement("div");
    grid.className = "grid";
    grid.appendChild(this._panel("Scene", this.snapshot().scene, "scene", documentRef));
    grid.appendChild(this._panel("Video", this.snapshot().video, "video", documentRef));
    grid.appendChild(this._metricsPanel(documentRef));
    grid.appendChild(this._eventsPanel(documentRef));
    this.root.appendChild(grid);
  }

  _syncVideo(video, mediaTime, mappingStatus) {
    this._videoTargetTime = mediaTime;
    if (mediaTime !== null && ["available", "partial"].includes(mappingStatus)) {
      const currentTime = finiteNumber(video.currentTime);
      if (currentTime === null || Math.abs(currentTime - mediaTime) > 1e-3) {
        try {
          video.currentTime = mediaTime;
        } catch (_error) {
          // Browsers can reject a seek before metadata loads; the mapping stays visible.
        }
      }
    }
    if (this.state.playing) {
      if (video.paused === true && typeof video.play === "function") {
        const playResult = video.play();
        playResult?.catch?.(() => {});
      }
    } else if (video.paused === false) {
      video.pause?.();
    }
  }

  _contextPanel(documentRef) {
    const section = documentRef.createElement("section");
    section.className = "context-panel muted";
    const context = this.model.context || {};
    const identity = this.model.source_identity || {};
    const identityIds = Object.keys(identity);
    const goalPoint = this.model.goal_geometry?.point?.value;
    const goalStatus = this.model.goal_geometry?.point?.status || "unavailable";
    const boundary = this.model.goal_geometry?.completion_boundary;
    const boundaryStatus = boundary?.status || "unavailable";
    section.textContent = [
      `campaign=${context.campaign_id || "unavailable"}`,
      `execution=${context.execution_id || "unavailable"}`,
      `episode=${context.episode_id || "unavailable"}`,
      `actor=${context.actor_id || "unavailable"}`,
      `source identities=${identityIds.length ? identityIds.join(",") : "unavailable"}`,
      `goal=${goalStatus}${goalPoint ? ` ${JSON.stringify(goalPoint)}` : ""}`,
      `completion boundary=${boundaryStatus}${boundary?.value ? ` ${JSON.stringify(boundary.value)}` : ""}`,
    ].join(" | ");
    return section;
  }

  _panel(title, snapshot, kind, documentRef) {
    const section = documentRef.createElement("section");
    section.className = "panel";
    const heading = documentRef.createElement("h2");
    heading.textContent = title;
    section.appendChild(heading);
    if (kind === "scene") {
      this._sceneMount = mountSceneViewer(section, this.model, snapshot);
    }
    if (kind === "video") {
      const uri = sourceVideoUri(this.model, snapshot);
      const mappingStatus = this.model.streams?.video?.status;
      const mediaTime = videoPresentationTime(snapshot.value);
      const mappingUsable =
        snapshot.status === "available" &&
        ["available", "partial"].includes(mappingStatus) &&
        mediaTime !== null;
      if (uri && mappingUsable && trustedOfflineMediaUri(uri, this._allowedMediaSchemes)) {
        let video = this._videoElement;
        if (!video || (video.ownerDocument && video.ownerDocument !== documentRef)) {
          video = documentRef.createElement("video");
          video.controls = true;
          video.muted = true;
          video.playsInline = true;
          video.preload = "metadata";
          video.className = "review-video";
          if (!video.dataset) video.dataset = {};
        }
        if (!video.dataset) video.dataset = {};
        this._bindControl(video, "loadedmetadata", () => {
          if (this._videoElement === video && this._videoTargetTime !== null) {
            this._syncVideo(video, this._videoTargetTime, "available");
          }
        });
        if (video.dataset.sourceUri !== uri) {
          video.dataset.sourceUri = uri;
          video.src = uri;
        }
        section.appendChild(video);
        this._videoElement = video;
        this._syncVideo(video, mediaTime, mappingStatus);
      } else {
        this._videoElement?.pause?.();
      }
    }
    const text = documentRef.createElement("p");
    text.className = snapshot.status === "available" ? "muted" : "unavailable";
    if (snapshot.status === "available") {
      text.textContent = `sample ${Number(snapshot.sample_time_s).toFixed(3)} s | error ${Number(snapshot.temporal_error_s).toFixed(3)} s | resolution ${Number(snapshot.resolution_s).toFixed(3)} s`;
      const pre = documentRef.createElement("pre");
      pre.textContent = JSON.stringify(snapshot.value, null, 2);
      section.appendChild(text);
      section.appendChild(pre);
    } else {
      text.textContent = `${kind} unavailable: ${snapshot.reason || "not recorded"} | resolution ${Number(snapshot.resolution_s || 0).toFixed(3)} s`;
      section.appendChild(text);
    }
    return section;
  }

  _metricsPanel(documentRef) {
    const section = documentRef.createElement("section");
    section.className = "panel";
    const heading = documentRef.createElement("h2");
    heading.textContent = "Metrics";
    section.appendChild(heading);
    for (const [metricId, metric] of Object.entries(this.snapshot().metrics)) {
      const row = documentRef.createElement("div");
      row.className = "metric-row";
      const toggle = documentRef.createElement("input");
      toggle.type = "checkbox";
      toggle.checked = metric.visible;
      this._bindControl(toggle, "click", (event) => event.stopPropagation());
      this._bindControl(toggle, "change", () => this.dispatch({ type: "toggle-metric", metric_id: metricId, source: "control" }));
      row.appendChild(toggle);
      const label = documentRef.createElement("span");
      const unit = metric.unit || "unit unavailable";
      const current = metric.current;
      label.textContent = `${metric.label} [${unit}] — ${current.status === "available" ? displayMetricValue(current.value) : `missing (${current.reason})`}`;
      row.appendChild(label);
      this._bindControl(row, "click", (event) => {
        if (event.target === toggle) return;
        this.dispatch({ type: "metric-seek", metric_id: metricId, source: "metric" });
      });
      if (metric.visible) {
        const trace = documentRef.createElement("div");
        trace.className = "metric-trace";
        for (const sample of metric.stream?.samples || []) {
          if (sample.missing || !Number.isFinite(Number(sample.time_s))) continue;
          const point = documentRef.createElement("button");
          point.type = "button";
          point.className = "metric-sample";
          point.dataset.timeS = String(sample.time_s);
          point.title = `${metric.label} at source time ${sample.time_s}`;
          point.textContent = "●";
          this._bindControl(point, "click", (event) => {
            event.stopPropagation();
            this.dispatch({ type: "metric-seek", metric_id: metricId, time_s: sample.time_s, source: "metric-sample" });
          });
          trace.appendChild(point);
        }
        row.appendChild(trace);
      }
      section.appendChild(row);
    }
    if (!Object.keys(this.model.metrics || {}).length) {
      const empty = documentRef.createElement("p");
      empty.className = "unavailable";
      empty.textContent = "unavailable: no metric series recorded";
      section.appendChild(empty);
    }
    return section;
  }

  _eventsPanel(documentRef) {
    const section = documentRef.createElement("section");
    section.className = "panel";
    const heading = documentRef.createElement("h2");
    heading.textContent = "Events";
    section.appendChild(heading);
    for (const event of this.snapshot().events) {
      const button = documentRef.createElement("button");
      button.type = "button";
      button.textContent = `${event.event_type} ${event.start_s}–${event.end_s}${event.selected ? " (selected)" : ""}`;
      this._bindControl(button, "click", () => this.dispatch({ type: "event-seek", event_id: event.event_id, source: "event" }));
      section.appendChild(button);
    }
    if (!this.model.events?.length) {
      const empty = documentRef.createElement("p");
      empty.className = "unavailable";
      empty.textContent = "unavailable: no event intervals recorded";
      section.appendChild(empty);
    }
    return section;
  }
}

export function createPanelController(model, root = null, options = {}) {
  return new ReviewPanelsController(model, root, options);
}

export function mountReviewPanels(model, root, options = {}) {
  return createPanelController(model, root, options);
}

const dataElement = typeof document === "undefined" ? null : document.getElementById("review-panels-data");
const root = typeof document === "undefined" ? null : document.getElementById("review-panels-root");
if (dataElement && root) {
  try {
    const model = JSON.parse(dataElement.textContent || "{}");
    mountReviewPanels(model, root);
  } catch (error) {
    root.textContent = `Unable to load review panel model: ${error}`;
  }
}
